//小説の言葉
export const novelWords = [
	{ kanji: "魔法", romaji: "mahou", eng: "magic" },
	{ kanji: "魔法使い", romaji: "mahoutukai", eng: "wizard" },
	{ kanji: "魔法陣", romaji: "mahoujinn", eng: "magic circle" },
	{ kanji: "呪文", romaji: "jyumonn", eng: "spell" },
	{ kanji: "杖", romaji: "tue", eng: "wand" },
	{ kanji: "剣", romaji: "kenn", eng: "sword" },
	{ kanji: "竜", romaji: "ryuu", eng: "dragon" },
	{ kanji: "魔王", romaji: "maou", eng: "demon king" },
	{ kanji: "冒険", romaji: "boukenn", eng: "adventure" },
	{ kanji: "騎士", romaji: "kisi", eng: "knight" },
	{ kanji: "冒険者", romaji: "boukennsya", eng: "adventurer" },
	{ kanji: "勇者", romaji: "yuusya", eng: "hero" },
	{ kanji: "魔獣", romaji: "majyuu", eng: "magical beast" },
	{ kanji: "召喚", romaji: "syoukann", eng: "summon" },
	{ kanji: "魔法剣", romaji: "mahoukenn", eng: "magic sword" },
	{ kanji: "魔力", romaji: "maryoku", eng: "magical power" },
	{ kanji: "ドラゴン", romaji: "doragonn", eng: "dragon" },
	{ kanji: "予言書", romaji: "yogennsyo", eng: "prophecy book" },
	{ kanji: "魔術", romaji: "majyutu", eng: "magic art" },
	{ kanji: "妖精", romaji: "yousei", eng: "fairy" },
	{ kanji: "幻獣", romaji: "gennjyuu", eng: "phantom beast" },
	{ kanji: "神話", romaji: "sinnwa", eng: "myth" },
	{ kanji: "魔法戦士", romaji: "mahousennsi", eng: "magic warrior" },
	{ kanji: "黒魔術", romaji: "kuromajyutu", eng: "black magic" },
	{ kanji: "聖剣", romaji: "seikenn", eng: "holy sword" },
	{ kanji: "魔界", romaji: "makai", eng: "demon world" },
	{ kanji: "魔法書", romaji: "mahousyo", eng: "magic book" },
	{ kanji: "魔女", romaji: "majyo", eng: "witch" },
	{ kanji: "魔法学校", romaji: "mahougakkou", eng: "magic school" },
	{ kanji: "宇宙船", romaji: "utyuusenn", eng: "spaceship" },
	{ kanji: "未来", romaji: "mirai", eng: "future" },
	{ kanji: "ロボット", romaji: "robotto", eng: "robot" },
	{ kanji: "クローン", romaji: "kuro-nn", eng: "clone" },
	{ kanji: "超能力", romaji: "tyounouryoku", eng: "psychic powers" },
	{ kanji: "タイムトラベル", romaji: "taimutoraberu", eng: "time travel" },
	{ kanji: "異星人", romaji: "iseijinn", eng: "extraterrestrial" },
	{ kanji: "宇宙", romaji: "utyuu", eng: "space" },
	{ kanji: "宇宙戦争", romaji: "utyuusensou", eng: "space war" },
	{ kanji: "サイバーパンク", romaji: "saiba-pannku", eng: "cyberpunk" },
	{ kanji: "パラレルワールド", romaji: "parareruwa-rudo", eng: "parallel world" },
	{ kanji: "人工知能", romaji: "jinnkoutinou", eng: "artificial intelligence" },
	{ kanji: "アンドロイド", romaji: "anndoroido", eng: "android" },
	{ kanji: "サイボーグ", romaji: "saibo-gu", eng: "cyborg" },
	{ kanji: "宇宙人", romaji: "utyuujinn", eng: "alien" },
	{ kanji: "ディストピア", romaji: "dhisutopia", eng: "dystopia" },
	{ kanji: "宇宙開発", romaji: "utyuukaihatu", eng: "space development" },
	{ kanji: "宇宙ステーション", romaji: "utyuusute-syonn", eng: "space station" },
	{ kanji: "宇宙探査", romaji: "utyuutannsa", eng: "space exploration" },
	{ kanji: "ロボット工学", romaji: "robottokougaku", eng: "robotics" },
	{ kanji: "宇宙旅行", romaji: "utyuuryokou", eng: "space travel" },
	{ kanji: "宇宙開拓", romaji: "utyuukaitaku", eng: "space colonization" },
	{ kanji: "宇宙時代", romaji: "utyuujidai", eng: "space age" },
	{ kanji: "宇宙エレベーター", romaji: "utyuuerebe-ta-", eng: "space elevator" },
	{ kanji: "宇宙戦艦", romaji: "utyuusennkann", eng: "space battleship" },
	{ kanji: "クローン技術", romaji: "kuro-nngijyutu", eng: "clone technology" },
	{ kanji: "テレポーテーション", romaji: "terepo-te-syonn", eng: "teleportation" },
	{ kanji: "宇宙移民", romaji: "utyuuiminn", eng: "space migration" },
	{ kanji: "人工衛星", romaji: "jinnkoueisei", eng: "artificial satellite" },
	{ kanji: "仮想現実", romaji: "kasougennjitu", eng: "virtual reality" },
	{ kanji: "サイバーネットワーク", romaji: "saiba-nettowa-ku", eng: "cyber network" },
	{ kanji: "グリッドコンピューティング", romaji: "guriddokonnpyu-thinngu", eng: "grid computing" },
	{ kanji: "バーチャルリアリティ", romaji: "ba-charuriarithi", eng: "virtual reality" },
	{ kanji: "アステロイド", romaji: "asuteroido", eng: "asteroid" },
	{ kanji: "惑星", romaji: "wakusei", eng: "planet" },
	{ kanji: "太陽系", romaji: "taiyoukei", eng: "solar system" },
	{ kanji: "恒星", romaji: "kousei", eng: "star" },
	{ kanji: "時空間", romaji: "jikuukann", eng: "spacetime" },
	{ kanji: "ブラックホール", romaji: "burakkuho-ru", eng: "black hole" },
	{ kanji: "宇宙論", romaji: "utyuuronn", eng: "cosmology" },
	{ kanji: "宇宙船乗組員", romaji: "utyuusennnorikumiinn", eng: "spaceship crew" },
	{ kanji: "宇宙エネルギー", romaji: "utyuuenerugi-", eng: "space energy" },
	{ kanji: "宇宙観測", romaji: "utyuukannsoku", eng: "space observation" },
	{ kanji: "宇宙ステーションクルー", romaji: "utyuusute-syonnkuru-", eng: "space station crew" },
	{ kanji: "宇宙線", romaji: "utyuusenn", eng: "cosmic rays" },
	{ kanji: "スペースコロニー", romaji: "supe-sukoroni-", eng: "space colony" },
	{ kanji: "テラフォーミング", romaji: "terafo-minngu", eng: "terraforming" },
	{ kanji: "サイボーグ技術", romaji: "saibo-gugijyutu", eng: "cyborg technology" },
	{
		kanji: "宇宙ステーションメンテナンス",
		romaji: "utyuusute-syonnmenntenannsu",
		eng: "space station maintenance"
	},
	{ kanji: "宇宙環境", romaji: "utyuukannkyou", eng: "space environment" },
	{ kanji: "惑星探査機", romaji: "wakuseitannsaki", eng: "planetary probe" },
	{ kanji: "宇宙探査機", romaji: "utyuutannsaki", eng: "space probe" },
	{ kanji: "地球外生命体", romaji: "tikyuugaiseimeitai", eng: "extraterrestrial life" },
	{ kanji: "サイバースペース", romaji: "saiba-supe-su", eng: "cyberspace" },
	{ kanji: "量子コンピューター", romaji: "ryousikonnpyu-ta-", eng: "quantum computer" },
	{ kanji: "テクノロジー", romaji: "tekunoroji-", eng: "technology" },
	{ kanji: "宇宙開発計画", romaji: "utyuukaihatukeikaku", eng: "space development plan" },
	{ kanji: "スペースシャトル", romaji: "supe-susyatoru", eng: "space shuttle" },
	{ kanji: "推理小説", romaji: "suirisyousetu", eng: "detective novel" },
	{ kanji: "事件", romaji: "jikenn", eng: "case" },
	{ kanji: "探偵", romaji: "tanntei", eng: "detective" },
	{ kanji: "ミステリー", romaji: "misuteri-", eng: "mystery" },
	{ kanji: "犯罪", romaji: "hannzai", eng: "crime" },
	{ kanji: "証拠", romaji: "syouko", eng: "evidence" },
	{ kanji: "アリバイ", romaji: "aribai", eng: "alibi" },
	{ kanji: "殺人", romaji: "satujinn", eng: "murder" },
	{ kanji: "謎", romaji: "nazo", eng: "puzzle" },
	{ kanji: "推理小説家", romaji: "suirisyousetuka", eng: "mystery writer" },
	{ kanji: "密室", romaji: "missitu", eng: "locked room" },
	{ kanji: "事件現場", romaji: "jikenngennba", eng: "crime scene" },
	{ kanji: "犯人", romaji: "hannninn", eng: "criminal" },
	{ kanji: "探偵助手", romaji: "tannteijyosyu", eng: "detective assistant" },
	{ kanji: "怪盗", romaji: "kaitou", eng: "phantom thief" },
	{ kanji: "暗号", romaji: "anngou", eng: "cipher" },
	{ kanji: "推理力", romaji: "suiriryoku", eng: "deductive reasoning" },
	{ kanji: "サスペンス", romaji: "sasupennsu", eng: "suspense" },
	{ kanji: "アクション", romaji: "akusyonn", eng: "action" },
	{ kanji: "探偵小説", romaji: "tannteisyousetu", eng: "detective novel" },
	{ kanji: "事件簿", romaji: "jikennbo", eng: "case file" },
	{ kanji: "密室殺人", romaji: "missitusatujinn", eng: "locked-room murder" },
	{ kanji: "探偵事務所", romaji: "tannteijimusyo", eng: "detective agency" },
	{ kanji: "証人", romaji: "syouninn", eng: "witness" },
	{ kanji: "事件解決", romaji: "jikennkaiketu", eng: "case resolution" },
	{ kanji: "黒幕", romaji: "kuromaku", eng: "mastermind" },
	{ kanji: "ノワール", romaji: "nowa-ru", eng: "noir" },
	{ kanji: "探偵小説の名探偵", romaji: "tannteisyousetunomeitanntei", eng: "famous detective in detective novels" },
	{ kanji: "犯罪捜査", romaji: "hannzaisousa", eng: "criminal investigation" },
	{ kanji: "証言", romaji: "syougenn", eng: "testimony" }
];

//ハンターハンター
export const hunterWords = [
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" }
];

//アニメ、漫画
export const comicAndAnimeWords = [
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" }
];

//ロマンス小説の言葉
export const romanceWords = [];

//時代小説の言葉
export const historyWords = [];

//ホラー小説の言葉
export const horrorWords = [];

//冒険小説の言葉
export const adventureWords = [];

//サスペンス小説の言葉
export const suspenseWords = [];
