//小説の言葉
export const novelWords = [
	{ kanji: "魔法", romaji: "mahou", eng: "magic" },
	{ kanji: "魔法使い", romaji: "mahoutukai", eng: "wizard" },
	{ kanji: "魔法陣", romaji: "mahoujinn", eng: "magic circle" },
	{ kanji: "呪文", romaji: "jyumonn", eng: "spell" },
	{ kanji: "杖", romaji: "tue", eng: "wand" },
	{ kanji: "剣", romaji: "kenn", eng: "sword" },
	{ kanji: "竜", romaji: "ryuu", eng: "dragon" },
	{ kanji: "魔王", romaji: "maou", eng: "demon king" },
	{ kanji: "冒険", romaji: "boukenn", eng: "adventure" },
	{ kanji: "騎士", romaji: "kisi", eng: "knight" },
	{ kanji: "冒険者", romaji: "boukennsya", eng: "adventurer" },
	{ kanji: "勇者", romaji: "yuusya", eng: "hero" },
	{ kanji: "魔獣", romaji: "majyuu", eng: "magical beast" },
	{ kanji: "召喚", romaji: "syoukann", eng: "summon" },
	{ kanji: "魔法剣", romaji: "mahoukenn", eng: "magic sword" },
	{ kanji: "魔力", romaji: "maryoku", eng: "magical power" },
	{ kanji: "ドラゴン", romaji: "doragonn", eng: "dragon" },
	{ kanji: "予言書", romaji: "yogennsyo", eng: "prophecy book" },
	{ kanji: "魔術", romaji: "majyutu", eng: "magic art" },
	{ kanji: "妖精", romaji: "yousei", eng: "fairy" },
	{ kanji: "幻獣", romaji: "gennjyuu", eng: "phantom beast" },
	{ kanji: "神話", romaji: "sinnwa", eng: "myth" },
	{ kanji: "魔法戦士", romaji: "mahousennsi", eng: "magic warrior" },
	{ kanji: "黒魔術", romaji: "kuromajyutu", eng: "black magic" },
	{ kanji: "聖剣", romaji: "seikenn", eng: "holy sword" },
	{ kanji: "魔界", romaji: "makai", eng: "demon world" },
	{ kanji: "魔法書", romaji: "mahousyo", eng: "magic book" },
	{ kanji: "魔女", romaji: "majyo", eng: "witch" },
	{ kanji: "魔法学校", romaji: "mahougakkou", eng: "magic school" },
	{ kanji: "宇宙船", romaji: "utyuusenn", eng: "spaceship" },
	{ kanji: "未来", romaji: "mirai", eng: "future" },
	{ kanji: "ロボット", romaji: "robotto", eng: "robot" },
	{ kanji: "クローン", romaji: "kuro-nn", eng: "clone" },
	{ kanji: "超能力", romaji: "tyounouryoku", eng: "psychic powers" },
	{ kanji: "タイムトラベル", romaji: "taimutoraberu", eng: "time travel" },
	{ kanji: "異星人", romaji: "iseijinn", eng: "extraterrestrial" },
	{ kanji: "宇宙", romaji: "utyuu", eng: "space" },
	{ kanji: "宇宙戦争", romaji: "utyuusensou", eng: "space war" },
	{ kanji: "サイバーパンク", romaji: "saiba-pannku", eng: "cyberpunk" },
	{ kanji: "パラレルワールド", romaji: "parareruwa-rudo", eng: "parallel world" },
	{ kanji: "人工知能", romaji: "jinnkoutinou", eng: "artificial intelligence" },
	{ kanji: "アンドロイド", romaji: "anndoroido", eng: "android" },
	{ kanji: "サイボーグ", romaji: "saibo-gu", eng: "cyborg" },
	{ kanji: "宇宙人", romaji: "utyuujinn", eng: "alien" },
	{ kanji: "ディストピア", romaji: "dhisutopia", eng: "dystopia" },
	{ kanji: "宇宙開発", romaji: "utyuukaihatu", eng: "space development" },
	{ kanji: "宇宙ステーション", romaji: "utyuusute-syonn", eng: "space station" },
	{ kanji: "宇宙探査", romaji: "utyuutannsa", eng: "space exploration" },
	{ kanji: "ロボット工学", romaji: "robottokougaku", eng: "robotics" },
	{ kanji: "宇宙旅行", romaji: "utyuuryokou", eng: "space travel" },
	{ kanji: "宇宙開拓", romaji: "utyuukaitaku", eng: "space colonization" },
	{ kanji: "宇宙時代", romaji: "utyuujidai", eng: "space age" },
	{ kanji: "宇宙エレベーター", romaji: "utyuuerebe-ta-", eng: "space elevator" },
	{ kanji: "宇宙戦艦", romaji: "utyuusennkann", eng: "space battleship" },
	{ kanji: "クローン技術", romaji: "kuro-nngijyutu", eng: "clone technology" },
	{ kanji: "テレポーテーション", romaji: "terepo-te-syonn", eng: "teleportation" },
	{ kanji: "宇宙移民", romaji: "utyuuiminn", eng: "space migration" },
	{ kanji: "人工衛星", romaji: "jinnkoueisei", eng: "artificial satellite" },
	{ kanji: "仮想現実", romaji: "kasougennjitu", eng: "virtual reality" },
	{ kanji: "サイバーネットワーク", romaji: "saiba-nettowa-ku", eng: "cyber network" },
	{ kanji: "グリッドコンピューティング", romaji: "guriddokonnpyu-thinngu", eng: "grid computing" },
	{ kanji: "バーチャルリアリティ", romaji: "ba-charuriarithi", eng: "virtual reality" },
	{ kanji: "アステロイド", romaji: "asuteroido", eng: "asteroid" },
	{ kanji: "惑星", romaji: "wakusei", eng: "planet" },
	{ kanji: "太陽系", romaji: "taiyoukei", eng: "solar system" },
	{ kanji: "恒星", romaji: "kousei", eng: "star" },
	{ kanji: "時空間", romaji: "jikuukann", eng: "spacetime" },
	{ kanji: "ブラックホール", romaji: "burakkuho-ru", eng: "black hole" },
	{ kanji: "宇宙論", romaji: "utyuuronn", eng: "cosmology" },
	{ kanji: "宇宙船乗組員", romaji: "utyuusennnorikumiinn", eng: "spaceship crew" },
	{ kanji: "宇宙エネルギー", romaji: "utyuuenerugi-", eng: "space energy" },
	{ kanji: "宇宙観測", romaji: "utyuukannsoku", eng: "space observation" },
	{ kanji: "宇宙ステーションクルー", romaji: "utyuusute-syonnkuru-", eng: "space station crew" },
	{ kanji: "宇宙線", romaji: "utyuusenn", eng: "cosmic rays" },
	{ kanji: "スペースコロニー", romaji: "supe-sukoroni-", eng: "space colony" },
	{ kanji: "テラフォーミング", romaji: "terafo-minngu", eng: "terraforming" },
	{ kanji: "サイボーグ技術", romaji: "saibo-gugijyutu", eng: "cyborg technology" },
	{
		kanji: "宇宙ステーションメンテナンス",
		romaji: "utyuusute-syonnmenntenannsu",
		eng: "space station maintenance"
	},
	{ kanji: "宇宙環境", romaji: "utyuukannkyou", eng: "space environment" },
	{ kanji: "惑星探査機", romaji: "wakuseitannsaki", eng: "planetary probe" },
	{ kanji: "宇宙探査機", romaji: "utyuutannsaki", eng: "space probe" },
	{ kanji: "地球外生命体", romaji: "tikyuugaiseimeitai", eng: "extraterrestrial life" },
	{ kanji: "サイバースペース", romaji: "saiba-supe-su", eng: "cyberspace" },
	{ kanji: "量子コンピューター", romaji: "ryousikonnpyu-ta-", eng: "quantum computer" },
	{ kanji: "テクノロジー", romaji: "tekunoroji-", eng: "technology" },
	{ kanji: "宇宙開発計画", romaji: "utyuukaihatukeikaku", eng: "space development plan" },
	{ kanji: "スペースシャトル", romaji: "supe-susyatoru", eng: "space shuttle" },
	{ kanji: "推理小説", romaji: "suirisyousetu", eng: "detective novel" },
	{ kanji: "事件", romaji: "jikenn", eng: "case" },
	{ kanji: "探偵", romaji: "tanntei", eng: "detective" },
	{ kanji: "ミステリー", romaji: "misuteri-", eng: "mystery" },
	{ kanji: "犯罪", romaji: "hannzai", eng: "crime" },
	{ kanji: "証拠", romaji: "syouko", eng: "evidence" },
	{ kanji: "アリバイ", romaji: "aribai", eng: "alibi" },
	{ kanji: "殺人", romaji: "satujinn", eng: "murder" },
	{ kanji: "謎", romaji: "nazo", eng: "puzzle" },
	{ kanji: "推理小説家", romaji: "suirisyousetuka", eng: "mystery writer" },
	{ kanji: "密室", romaji: "missitu", eng: "locked room" },
	{ kanji: "事件現場", romaji: "jikenngennba", eng: "crime scene" },
	{ kanji: "犯人", romaji: "hannninn", eng: "criminal" },
	{ kanji: "探偵助手", romaji: "tannteijyosyu", eng: "detective assistant" },
	{ kanji: "怪盗", romaji: "kaitou", eng: "phantom thief" },
	{ kanji: "暗号", romaji: "anngou", eng: "cipher" },
	{ kanji: "推理力", romaji: "suiriryoku", eng: "deductive reasoning" },
	{ kanji: "サスペンス", romaji: "sasupennsu", eng: "suspense" },
	{ kanji: "アクション", romaji: "akusyonn", eng: "action" },
	{ kanji: "探偵小説", romaji: "tannteisyousetu", eng: "detective novel" },
	{ kanji: "事件簿", romaji: "jikennbo", eng: "case file" },
	{ kanji: "密室殺人", romaji: "missitusatujinn", eng: "locked-room murder" },
	{ kanji: "探偵事務所", romaji: "tannteijimusyo", eng: "detective agency" },
	{ kanji: "証人", romaji: "syouninn", eng: "witness" },
	{ kanji: "事件解決", romaji: "jikennkaiketu", eng: "case resolution" },
	{ kanji: "黒幕", romaji: "kuromaku", eng: "mastermind" },
	{ kanji: "ノワール", romaji: "nowa-ru", eng: "noir" },
	{ kanji: "探偵小説の名探偵", romaji: "tannteisyousetunomeitanntei", eng: "famous detective in detective novels" },
	{ kanji: "犯罪捜査", romaji: "hannzaisousa", eng: "criminal investigation" },
	{ kanji: "証言", romaji: "syougenn", eng: "testimony" }
];

//ハンターハンター
export const hunterWords = [
	{ kanji: "百式観音", romaji: "hyakusikikannnonn", eng: "ひゃくしきかんのん" },
	{ kanji: "百式観音壱乃掌", romaji: "hyakusikikannnonnitinote", eng: "ひゃくしきかんのんいちのて" },
	{ kanji: "百式観音零の掌", romaji: "hyakusikikannnonnzeronote", eng: "ひゃくしきかんのんぜろのて" },
	{ kanji: "百式観音九十九の掌", romaji: "hyakusikikannnonntukumonote", eng: "つくものて" },
	{ kanji: "蚤弾", romaji: "huri-damu", eng: "フリーダム" },
	{ kanji: "死体と遊ぶな子供達", romaji: "sitaitoazobunakodomotati", eng: "リビングデッドドールズ" },
	{ kanji: "180分の恋奴隷", romaji: "hyakuhatijyuppunnnokoidorei", eng: "インスタントラヴァー" },
	{ kanji: "俤人", romaji: "omokagebito", eng: "ソウルドール" },
	{ kanji: "魂呼ばい", romaji: "tamayobai", eng: "たまよばい" },
	{ kanji: "人形受胎", romaji: "ninngyoujyutai", eng: "ドールキャッチャー" },
	{ kanji: "死亡遊戯", romaji: "sibouyuugi", eng: "ダツDEダーツ" },
	{ kanji: "百万回生きた猫", romaji: "hyakumannkaiikitaneko", eng: "ネコノナマエ" },
	{ kanji: "気狂いピエロ", romaji: "kiguruipiero", eng: "クレイジースロット" },
	{ kanji: "死神の円舞曲", romaji: "sinigaminoennbukyoku", eng: "サイレントワルツ" },
	{ kanji: "踊る気儘な火人形", romaji: "odorukimamanahininngyou", eng: "ダンシングドール" },
	{ kanji: "虎咬真拳", romaji: "kokousinnkenn", eng: "ここうしんけん" },
	{ kanji: "2人セゾン", romaji: "hutarisezonn", eng: "キミガイナイ" },
	{ kanji: "蛇咬の舞", romaji: "dakounomai", eng: "だこうのまい" },
	{ kanji: "散弾独楽哀歌", romaji: "sanndanngomaaika", eng: "ショットガンブルース" },
	{ kanji: "戦闘舞踏曲", romaji: "senntoubutoukyoku", eng: "戦いのワルツ" },
	{ kanji: "竜巻独楽", romaji: "tatumakigoma", eng: "たつまきごま" },
	{ kanji: "超不協輪怨", romaji: "tyouhukyouwaonn", eng: "シークレットノイズ" },
	{ kanji: "雷掌", romaji: "kaminarisyou", eng: "イズツシ" },
	{ kanji: "神速", romaji: "sinnsoku", eng: "カンムル" },
	{ kanji: "落雷", romaji: "rakurai", eng: "ナルカミ" },
	{ kanji: "絶対時間", romaji: "zettaijikann", eng: "エンペラータイム" },
	{ kanji: "律する小指の鎖", romaji: "rissurukoyubinokusari", eng: "ジャッジメントチェーン" },
	{ kanji: "奪う人差し指の鎖", romaji: "ubauhitosasiyubinokusari", eng: "スチールチェーン" },
	{ kanji: "導く薬指の鎖", romaji: "mitibikukusuriyubinokusari", eng: "ダウジングチェーン" },
	{ kanji: "束縛する中指の鎖", romaji: "sokubakusurunakayubinokusari", eng: "チェーンジェイル" },
	{ kanji: "癒す親指の鎖", romaji: "iyasuoyayubinokusari", eng: "ホーリーチェーン" },
	{ kanji: "密室遊魚", romaji: "missituyuugyo", eng: "インドアフィッシュ" },
	{ kanji: "人間の証明", romaji: "ninngennnosyoumei", eng: "オーダースタンプ" },
	{ kanji: "転校生", romaji: "tennkousei", eng: "コンバートハンズ" },
	{ kanji: "番いの破壊者", romaji: "tugainohakaisya", eng: "サンアンドムーン" },
	{ kanji: "盗賊の極意", romaji: "sukiruhannta-", eng: "スキルハンター" },
	{ kanji: "栞のテーマ", romaji: "siorinote-ma", eng: "ダブルフェイス" },
	{ kanji: "一握りの火薬", romaji: "hitonigirinokayaku", eng: "リトルフラワー" },
	{ kanji: "神の左手悪魔の右手", romaji: "kaminohidariteakumanomigite", eng: "ギャラリーフェイク" },
	{ kanji: "黒い賢人", romaji: "kuroikennjinn", eng: "ブラックゴレイヌ" },
	{ kanji: "白い賢人", romaji: "siroikennjinn", eng: "ホワイトゴレイヌ" },
	{ kanji: "ジャジャン拳", romaji: "jyajyannkenn", eng: "じゃじゃんけん" },
	{ kanji: "血いさな世界", romaji: "tiisanasekai", eng: "ブラッディメアリー" },
	{ kanji: "審美的転生注射", romaji: "sinnbiganntekitennseityuusya", eng: "クイーンショット" },
	{ kanji: "遊戯王", romaji: "yuugiou", eng: "カルドセプト" },
	{ kanji: "デメちゃん", romaji: "demetyann", eng: "でめちゃん" },
	{ kanji: "大和撫子七変化", romaji: "yamatonadesikositihennge", eng: "ライダーズハイ" },
	{ kanji: "麟粉乃愛泉", romaji: "rinnpunnnoaisenn", eng: "スピリチュアルメッセージ" },
	{ kanji: "蠅の王", romaji: "haenoou", eng: "ベルゼブブ" },
	{ kanji: "縁の下の十一人", romaji: "ennnositanojyuuitininn", eng: "イレブンブラックチルドレン" },
	{ kanji: "携帯する他人の運命", romaji: "keitaisurutaninnnounnmei", eng: "ブラックボイス" },
	{ kanji: "暗い宿", romaji: "kuraiyado", eng: "ホテル・ラフレシア" },
	{ kanji: "物真似鳥", romaji: "monomanedori", eng: "ジェイプシフター" },
	{ kanji: "機械に巣食う棘", romaji: "kikainisukuutoge", eng: "マシンイーター" },
	{ kanji: "龍星群", romaji: "ryuuseigunn", eng: "ドラゴンダイヴ" },
	{ kanji: "龍頭戯画", romaji: "ryuutougiga", eng: "ドラゴンヘッド" },
	{ kanji: "牙突", romaji: "gatotu", eng: "ドランゴンランス" },
	{ kanji: "蠅の仕事", romaji: "haenosigoto", eng: "サイレントワーカー" },
	{ kanji: "天上不知唯我独損", romaji: "tennjyouhutiyuigadokusonn", eng: "ハコワレ" },
	{ kanji: "天使の自動筆記", romaji: "tennsinojidousyoki", eng: "ラブリーゴーストライター" },
	{ kanji: "黒子無想", romaji: "kurokomusou", eng: "テレプシコーラ" },
	{ kanji: "玩具修理者", romaji: "ganngusyuurisya", eng: "ドクタープライス" },
	{ kanji: "窓を開く者", romaji: "madowohirakumono", eng: "スクリーム" },
	{ kanji: "4次元マンション", romaji: "yojigennmannsyonn", eng: "ハイドアンドシーク" },
	{ kanji: "淋しい深海魚", romaji: "samisiisinnkaigyo", eng: "ウインクブルー" },
	{ kanji: "暗黒の鬼婦神", romaji: "annkokunokihujinn", eng: "ブラックウィドウ" },
	{ kanji: "愛の放射線", romaji: "ainohousyasenn", eng: "ラブシャワー" },
	{ kanji: "記憶弾", romaji: "kiokudann", eng: "メモリーボム" },
	{ kanji: "流離の大俳人", romaji: "sasurainodaihaijinn", eng: "グレイトハイカー" },
	{ kanji: "凶器の錯乱", romaji: "kyoukinosakurann", eng: "いま殺りにゆきます" },
	{ kanji: "幽体離脱", romaji: "yuutairidatu", eng: "ザタッチ" },
	{ kanji: "桃色吐息", romaji: "momoirotoiki", eng: "ピアノマッサージ" },
	{ kanji: "魔法美容師", romaji: "mahoubiyousi", eng: "マジカルエステ" },
	{ kanji: "薄っぺらな嘘", romaji: "usupperanauso", eng: "ドッキリテクスチャー" },
	{ kanji: "伸縮自在の愛", romaji: "sinnsyukujizainoai", eng: "バンジーガム" },
	{ kanji: "切り裂き美容師", romaji: "kirisakibiyousi", eng: "シザーハンズ" },
	{ kanji: "てのひらを太陽に", romaji: "tenohiranitaiyouwo", eng: "バイオハザード" },
	{ kanji: "廻天", romaji: "kaitenn", eng: "リッパー・サイクロトロン" },
	{ kanji: "秘密の扉", romaji: "himitunotobira", eng: "マジカルワーム" },
	{ kanji: "許されざる者", romaji: "yurusarezarumono", eng: "ペインパッカー" },
	{ kanji: "太陽に灼かれて", romaji: "taiyouniyakarete", eng: "ライジングサン" },
	{ kanji: "不思議で便利な大風呂敷", romaji: "husigidebennrinaooburosiki", eng: "ファンファンクロス" },
	{ kanji: "超複眼", romaji: "tyouhukugann", eng: "スーパーアイ" },
	{ kanji: "俺の両手は機関銃", romaji: "orenoryoutehamasinngann", eng: "ダブルマシンガン" },
	{ kanji: "裏窓の鳥", romaji: "uramadonotori", eng: "シークレットウインドウ" },
	{ kanji: "星を継ぐもの", romaji: "hosiwotugumono", eng: "ベンジャミンバトン" },
	{ kanji: "七色弓箭", romaji: "reinnbou", eng: "レインボウ" },
	{ kanji: "戦闘演武曲", romaji: "senntouennbukyoku", eng: "バト＝レ・カンタービレ" },
	{ kanji: "念糸縫合", romaji: "nennsihougou", eng: "ねんしほうごう" },
	{ kanji: "Zombie・Giri", romaji: "zombiegiri", eng: "ラ・ヴィアン・ローズ" },
	{ kanji: "密室裁判", romaji: "missitusaibann", eng: "クロスゲーム" },
	{ kanji: "神の共犯者", romaji: "kaminokyouhannsya", eng: "かみのきょうはんしゃ" },
	{ kanji: "神の不在証明", romaji: "kaminohuzaisyoumei", eng: "パーフェクトプラン" },
	{ kanji: "監獄ロック", romaji: "kanngokurokku", eng: "スモーキージェイル" },
	{ kanji: "紫煙機兵隊", romaji: "siennkiheitai", eng: "ディープパープル" },
	{ kanji: "恋のエチュード", romaji: "koinoetyu-do", eng: "サイキンオセン" },
	{ kanji: "墨攻", romaji: "bokukou", eng: "LSDF" },
	{ kanji: "爆発的推進力", romaji: "bakuhatutekisuisinnryoku", eng: "オーラバースト" },
	{ kanji: "双頭の蛇の正体", romaji: "soutounohebinosyoutai", eng: "サンダースネイク" },
	{ kanji: "双頭の蛇による二重唱", romaji: "soutounohebiniyorunijyuusou", eng: "ソングオブディフェンス" },
	{ kanji: "体は全部知っている", romaji: "karadahazennbusitteiru", eng: "ボディアンドソウル" },
	{ kanji: "14人の悪魔", romaji: "jyuuyoninnnoakuma", eng: "じゅうよにんのあくま" },
	{ kanji: "TUBE", romaji: "tubu", eng: "イナムラ" },
	{ kanji: "渦波", romaji: "uzunami", eng: "トルネイヴ" },
	{ kanji: "大波", romaji: "oonami", eng: "ビックウォール" },
	{ kanji: "謝債発行機", romaji: "syasaihakkouki", eng: "レンタルポッド" },
	{ kanji: "漆黒の処刑台", romaji: "sikkokunosyokeidai", eng: "オンバサラ" },
	{ kanji: "卵男", romaji: "tamagootoko", eng: "ミサイルマン" },
	{ kanji: "超破壊拳", romaji: "tyouhakaikenn", eng: "ビックバンインパクト" },
	{ kanji: "裏窓", romaji: "uramado", eng: "リトルアイ" },
	{ kanji: "命の音", romaji: "inotinooto", eng: "カウントダウン" },
	{ kanji: "11人いる", romaji: "jyuuitininniru", eng: "サイレントマジョリティ" },
	{ kanji: "damage", romaji: "damage", eng: "ダメージ" }
];

//アニメ、漫画
export const comicAndAnimeWords = [
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" },
	{ kanji: "", romaji: "", eng: "" }
];

//ロマンス小説の言葉
export const romanceWords = [];

//時代小説の言葉
export const historyWords = [];

//ホラー小説の言葉
export const horrorWords = [];

//冒険小説の言葉
export const adventureWords = [];

//サスペンス小説の言葉
export const suspenseWords = [];
