import { WordList } from "./typingProblems";

//ハンターハンター
export const hunterWords: WordList[] = [
	{
		kanji: "<Ruby>百式観音<rt>ひゃくしきかんのん</rt></Ruby>",
		romaji: "hyakusikikannnon",
		eng: "hyakusikikannnon",
		validInputs: [
			"hyakusikikannnon",
			"hyakusikicannnon",
			"hyakushikikannnon",
			"hyakushikicannnon",
			"hyakucikikannnon",
			"hyakucikicannnon",
			"hyacusikikannnon",
			"hyacusikicannnon",
			"hyacushikikannnon",
			"hyacushikicannnon",
			"hyacucikikannnon",
			"hyacucikicannnon",
			"hyaqusikikannnon",
			"hyaqusikicannnon",
			"hyaqushikikannnon",
			"hyaqushikicannnon",
			"hyaqucikikannnon",
			"hyaqucikicannnon"
		],
		validInputs2: [
			"hyakusikikannnon",
			"hyakusikicannnon",
			"hyakushikikannnon",
			"hyakushikicannnon",
			"hyakucikikannnon",
			"hyakucikicannnon",
			"hyacusikikannnon",
			"hyacusikicannnon",
			"hyacushikikannnon",
			"hyacushikicannnon",
			"hyacucikikannnon",
			"hyacucikicannnon",
			"hyaqusikikannnon",
			"hyaqusikicannnon",
			"hyaqushikikannnon",
			"hyaqushikicannnon",
			"hyaqucikikannnon",
			"hyaqucikicannnon"
		]
	},
	{
		kanji: "<Ruby>百式観音壱乃掌<rt>ひゃくしきかんのんいちのて</rt></Ruby>",
		romaji: "hyakusikikannnonnitinote",
		eng: "hyakusikikannnonnitinote",
		validInputs: [
			"hyakusikikannnonnitinote",
			"hyakusikikannnonnichinote",
			"hyakusikicannnonnitinote",
			"hyakusikicannnonnichinote",
			"hyakushikikannnonnitinote",
			"hyakushikikannnonnichinote",
			"hyakushikicannnonnitinote",
			"hyakushikicannnonnichinote",
			"hyakucikikannnonnitinote",
			"hyakucikikannnonnichinote",
			"hyakucikicannnonnitinote",
			"hyakucikicannnonnichinote",
			"hyacusikikannnonnitinote",
			"hyacusikikannnonnichinote",
			"hyacusikicannnonnitinote",
			"hyacusikicannnonnichinote",
			"hyacushikikannnonnitinote",
			"hyacushikikannnonnichinote",
			"hyacushikicannnonnitinote",
			"hyacushikicannnonnichinote",
			"hyacucikikannnonnitinote",
			"hyacucikikannnonnichinote",
			"hyacucikicannnonnitinote",
			"hyacucikicannnonnichinote",
			"hyaqusikikannnonnitinote",
			"hyaqusikikannnonnichinote",
			"hyaqusikicannnonnitinote",
			"hyaqusikicannnonnichinote",
			"hyaqushikikannnonnitinote",
			"hyaqushikikannnonnichinote",
			"hyaqushikicannnonnitinote",
			"hyaqushikicannnonnichinote",
			"hyaqucikikannnonnitinote",
			"hyaqucikikannnonnichinote",
			"hyaqucikicannnonnitinote",
			"hyaqucikicannnonnichinote"
		],
		validInputs2: [
			"hyakusikikannnonnitinote",
			"hyakusikikannnonnichinote",
			"hyakusikicannnonnitinote",
			"hyakusikicannnonnichinote",
			"hyakushikikannnonnitinote",
			"hyakushikikannnonnichinote",
			"hyakushikicannnonnitinote",
			"hyakushikicannnonnichinote",
			"hyakucikikannnonnitinote",
			"hyakucikikannnonnichinote",
			"hyakucikicannnonnitinote",
			"hyakucikicannnonnichinote",
			"hyacusikikannnonnitinote",
			"hyacusikikannnonnichinote",
			"hyacusikicannnonnitinote",
			"hyacusikicannnonnichinote",
			"hyacushikikannnonnitinote",
			"hyacushikikannnonnichinote",
			"hyacushikicannnonnitinote",
			"hyacushikicannnonnichinote",
			"hyacucikikannnonnitinote",
			"hyacucikikannnonnichinote",
			"hyacucikicannnonnitinote",
			"hyacucikicannnonnichinote",
			"hyaqusikikannnonnitinote",
			"hyaqusikikannnonnichinote",
			"hyaqusikicannnonnitinote",
			"hyaqusikicannnonnichinote",
			"hyaqushikikannnonnitinote",
			"hyaqushikikannnonnichinote",
			"hyaqushikicannnonnitinote",
			"hyaqushikicannnonnichinote",
			"hyaqucikikannnonnitinote",
			"hyaqucikikannnonnichinote",
			"hyaqucikicannnonnitinote",
			"hyaqucikicannnonnichinote"
		]
	},
	{
		kanji: "<Ruby>百式観音零の掌<rt>ひゃくしきかんのんぜろのて</rt></Ruby>",
		romaji: "hyakusikikannnonzeronote",
		eng: "hyakusikikannnonzeronote",
		validInputs: [
			"hyakusikikannnonzeronote",
			"hyakusikicannnonzeronote",
			"hyakushikikannnonzeronote",
			"hyakushikicannnonzeronote",
			"hyakucikikannnonzeronote",
			"hyakucikicannnonzeronote",
			"hyacusikikannnonzeronote",
			"hyacusikicannnonzeronote",
			"hyacushikikannnonzeronote",
			"hyacushikicannnonzeronote",
			"hyacucikikannnonzeronote",
			"hyacucikicannnonzeronote",
			"hyaqusikikannnonzeronote",
			"hyaqusikicannnonzeronote",
			"hyaqushikikannnonzeronote",
			"hyaqushikicannnonzeronote",
			"hyaqucikikannnonzeronote",
			"hyaqucikicannnonzeronote"
		],
		validInputs2: [
			"hyakusikikannnonzeronote",
			"hyakusikicannnonzeronote",
			"hyakushikikannnonzeronote",
			"hyakushikicannnonzeronote",
			"hyakucikikannnonzeronote",
			"hyakucikicannnonzeronote",
			"hyacusikikannnonzeronote",
			"hyacusikicannnonzeronote",
			"hyacushikikannnonzeronote",
			"hyacushikicannnonzeronote",
			"hyacucikikannnonzeronote",
			"hyacucikicannnonzeronote",
			"hyaqusikikannnonzeronote",
			"hyaqusikicannnonzeronote",
			"hyaqushikikannnonzeronote",
			"hyaqushikicannnonzeronote",
			"hyaqucikikannnonzeronote",
			"hyaqucikicannnonzeronote"
		]
	},
	{
		kanji: "<Ruby>百式観音九十九の掌<rt>ひゃくしきかんのんつくものて</rt></Ruby>",
		romaji: "hyakusikikannnontukumonote",
		eng: "hyakusikikannnontukumonote",
		validInputs: [
			"hyakusikikannnontukumonote",
			"hyakusikikannnontucumonote",
			"hyakusikikannnontuqumonote",
			"hyakusikikannnontsukumonote",
			"hyakusikikannnontsucumonote",
			"hyakusikikannnontsuqumonote",
			"hyakusikicannnontukumonote",
			"hyakusikicannnontucumonote",
			"hyakusikicannnontuqumonote",
			"hyakusikicannnontsukumonote",
			"hyakusikicannnontsucumonote",
			"hyakusikicannnontsuqumonote",
			"hyakushikikannnontukumonote",
			"hyakushikikannnontucumonote",
			"hyakushikikannnontuqumonote",
			"hyakushikikannnontsukumonote",
			"hyakushikikannnontsucumonote",
			"hyakushikikannnontsuqumonote",
			"hyakushikicannnontukumonote",
			"hyakushikicannnontucumonote",
			"hyakushikicannnontuqumonote",
			"hyakushikicannnontsukumonote",
			"hyakushikicannnontsucumonote",
			"hyakushikicannnontsuqumonote",
			"hyakucikikannnontukumonote",
			"hyakucikikannnontucumonote",
			"hyakucikikannnontuqumonote",
			"hyakucikikannnontsukumonote",
			"hyakucikikannnontsucumonote",
			"hyakucikikannnontsuqumonote",
			"hyakucikicannnontukumonote",
			"hyakucikicannnontucumonote",
			"hyakucikicannnontuqumonote",
			"hyakucikicannnontsukumonote",
			"hyakucikicannnontsucumonote",
			"hyakucikicannnontsuqumonote",
			"hyacusikikannnontukumonote",
			"hyacusikikannnontucumonote",
			"hyacusikikannnontuqumonote",
			"hyacusikikannnontsukumonote",
			"hyacusikikannnontsucumonote",
			"hyacusikikannnontsuqumonote",
			"hyacusikicannnontukumonote",
			"hyacusikicannnontucumonote",
			"hyacusikicannnontuqumonote",
			"hyacusikicannnontsukumonote",
			"hyacusikicannnontsucumonote",
			"hyacusikicannnontsuqumonote",
			"hyacushikikannnontukumonote",
			"hyacushikikannnontucumonote",
			"hyacushikikannnontuqumonote",
			"hyacushikikannnontsukumonote",
			"hyacushikikannnontsucumonote",
			"hyacushikikannnontsuqumonote",
			"hyacushikicannnontukumonote",
			"hyacushikicannnontucumonote",
			"hyacushikicannnontuqumonote",
			"hyacushikicannnontsukumonote",
			"hyacushikicannnontsucumonote",
			"hyacushikicannnontsuqumonote",
			"hyacucikikannnontukumonote",
			"hyacucikikannnontucumonote",
			"hyacucikikannnontuqumonote",
			"hyacucikikannnontsukumonote",
			"hyacucikikannnontsucumonote",
			"hyacucikikannnontsuqumonote",
			"hyacucikicannnontukumonote",
			"hyacucikicannnontucumonote",
			"hyacucikicannnontuqumonote",
			"hyacucikicannnontsukumonote",
			"hyacucikicannnontsucumonote",
			"hyacucikicannnontsuqumonote",
			"hyaqusikikannnontukumonote",
			"hyaqusikikannnontucumonote",
			"hyaqusikikannnontuqumonote",
			"hyaqusikikannnontsukumonote",
			"hyaqusikikannnontsucumonote",
			"hyaqusikikannnontsuqumonote",
			"hyaqusikicannnontukumonote",
			"hyaqusikicannnontucumonote",
			"hyaqusikicannnontuqumonote",
			"hyaqusikicannnontsukumonote",
			"hyaqusikicannnontsucumonote",
			"hyaqusikicannnontsuqumonote",
			"hyaqushikikannnontukumonote",
			"hyaqushikikannnontucumonote",
			"hyaqushikikannnontuqumonote",
			"hyaqushikikannnontsukumonote",
			"hyaqushikikannnontsucumonote",
			"hyaqushikikannnontsuqumonote",
			"hyaqushikicannnontukumonote",
			"hyaqushikicannnontucumonote",
			"hyaqushikicannnontuqumonote",
			"hyaqushikicannnontsukumonote",
			"hyaqushikicannnontsucumonote",
			"hyaqushikicannnontsuqumonote",
			"hyaqucikikannnontukumonote",
			"hyaqucikikannnontucumonote",
			"hyaqucikikannnontuqumonote",
			"hyaqucikikannnontsukumonote",
			"hyaqucikikannnontsucumonote",
			"hyaqucikikannnontsuqumonote",
			"hyaqucikicannnontukumonote",
			"hyaqucikicannnontucumonote",
			"hyaqucikicannnontuqumonote",
			"hyaqucikicannnontsukumonote",
			"hyaqucikicannnontsucumonote",
			"hyaqucikicannnontsuqumonote"
		],
		validInputs2: [
			"hyakusikikannnontukumonote",
			"hyakusikikannnontucumonote",
			"hyakusikikannnontuqumonote",
			"hyakusikikannnontsukumonote",
			"hyakusikikannnontsucumonote",
			"hyakusikikannnontsuqumonote",
			"hyakusikicannnontukumonote",
			"hyakusikicannnontucumonote",
			"hyakusikicannnontuqumonote",
			"hyakusikicannnontsukumonote",
			"hyakusikicannnontsucumonote",
			"hyakusikicannnontsuqumonote",
			"hyakushikikannnontukumonote",
			"hyakushikikannnontucumonote",
			"hyakushikikannnontuqumonote",
			"hyakushikikannnontsukumonote",
			"hyakushikikannnontsucumonote",
			"hyakushikikannnontsuqumonote",
			"hyakushikicannnontukumonote",
			"hyakushikicannnontucumonote",
			"hyakushikicannnontuqumonote",
			"hyakushikicannnontsukumonote",
			"hyakushikicannnontsucumonote",
			"hyakushikicannnontsuqumonote",
			"hyakucikikannnontukumonote",
			"hyakucikikannnontucumonote",
			"hyakucikikannnontuqumonote",
			"hyakucikikannnontsukumonote",
			"hyakucikikannnontsucumonote",
			"hyakucikikannnontsuqumonote",
			"hyakucikicannnontukumonote",
			"hyakucikicannnontucumonote",
			"hyakucikicannnontuqumonote",
			"hyakucikicannnontsukumonote",
			"hyakucikicannnontsucumonote",
			"hyakucikicannnontsuqumonote",
			"hyacusikikannnontukumonote",
			"hyacusikikannnontucumonote",
			"hyacusikikannnontuqumonote",
			"hyacusikikannnontsukumonote",
			"hyacusikikannnontsucumonote",
			"hyacusikikannnontsuqumonote",
			"hyacusikicannnontukumonote",
			"hyacusikicannnontucumonote",
			"hyacusikicannnontuqumonote",
			"hyacusikicannnontsukumonote",
			"hyacusikicannnontsucumonote",
			"hyacusikicannnontsuqumonote",
			"hyacushikikannnontukumonote",
			"hyacushikikannnontucumonote",
			"hyacushikikannnontuqumonote",
			"hyacushikikannnontsukumonote",
			"hyacushikikannnontsucumonote",
			"hyacushikikannnontsuqumonote",
			"hyacushikicannnontukumonote",
			"hyacushikicannnontucumonote",
			"hyacushikicannnontuqumonote",
			"hyacushikicannnontsukumonote",
			"hyacushikicannnontsucumonote",
			"hyacushikicannnontsuqumonote",
			"hyacucikikannnontukumonote",
			"hyacucikikannnontucumonote",
			"hyacucikikannnontuqumonote",
			"hyacucikikannnontsukumonote",
			"hyacucikikannnontsucumonote",
			"hyacucikikannnontsuqumonote",
			"hyacucikicannnontukumonote",
			"hyacucikicannnontucumonote",
			"hyacucikicannnontuqumonote",
			"hyacucikicannnontsukumonote",
			"hyacucikicannnontsucumonote",
			"hyacucikicannnontsuqumonote",
			"hyaqusikikannnontukumonote",
			"hyaqusikikannnontucumonote",
			"hyaqusikikannnontuqumonote",
			"hyaqusikikannnontsukumonote",
			"hyaqusikikannnontsucumonote",
			"hyaqusikikannnontsuqumonote",
			"hyaqusikicannnontukumonote",
			"hyaqusikicannnontucumonote",
			"hyaqusikicannnontuqumonote",
			"hyaqusikicannnontsukumonote",
			"hyaqusikicannnontsucumonote",
			"hyaqusikicannnontsuqumonote",
			"hyaqushikikannnontukumonote",
			"hyaqushikikannnontucumonote",
			"hyaqushikikannnontuqumonote",
			"hyaqushikikannnontsukumonote",
			"hyaqushikikannnontsucumonote",
			"hyaqushikikannnontsuqumonote",
			"hyaqushikicannnontukumonote",
			"hyaqushikicannnontucumonote",
			"hyaqushikicannnontuqumonote",
			"hyaqushikicannnontsukumonote",
			"hyaqushikicannnontsucumonote",
			"hyaqushikicannnontsuqumonote",
			"hyaqucikikannnontukumonote",
			"hyaqucikikannnontucumonote",
			"hyaqucikikannnontuqumonote",
			"hyaqucikikannnontsukumonote",
			"hyaqucikikannnontsucumonote",
			"hyaqucikikannnontsuqumonote",
			"hyaqucikicannnontukumonote",
			"hyaqucikicannnontucumonote",
			"hyaqucikicannnontuqumonote",
			"hyaqucikicannnontsukumonote",
			"hyaqucikicannnontsucumonote",
			"hyaqucikicannnontsuqumonote"
		]
	},
	{
		kanji: "<Ruby>蚤弾<rt>フリーダム</rt></Ruby>",
		romaji: "nomidan",
		eng: "huri-damu",
		validInputs: ["nomidan"],
		validInputs2: ["huri-damu", "furi-damu"]
	},
	{
		kanji: "<Ruby>死体と遊ぶな子供達<rt>リビングデッドドールズ</rt></Ruby>",
		romaji: "sitaitoasobunakodomotati",
		eng: "ribinngudeddodo-ruzu",
		validInputs: [
			"sitaitoasobunakodomotati",
			"sitaitoasobunakodomotachi",
			"sitaitoasobunacodomotati",
			"sitaitoasobunacodomotachi",
			"shitaitoasobunakodomotati",
			"shitaitoasobunakodomotachi",
			"shitaitoasobunacodomotati",
			"shitaitoasobunacodomotachi",
			"citaitoasobunakodomotati",
			"citaitoasobunakodomotachi",
			"citaitoasobunacodomotati",
			"citaitoasobunacodomotachi"
		],
		validInputs2: ["ribingudeddodo-ruzu", "ribinngudeddodo-ruzu"]
	},
	{
		kanji: "<Ruby>180分の恋奴隷<rt>インスタントラヴァー</rt></Ruby>",
		romaji: "180hunnnokoidorei",
		eng: "innsutantorava-",
		validInputs: ["180hunnnokoidorei", "180hunnnocoidorei", "180funnnokoidorei", "180funnnocoidorei"],
		validInputs2: ["insutantorava-", "innsutantorava-"]
	},
	{
		kanji: "<Ruby>俤人<rt>ソウルドール</rt></Ruby>",
		romaji: "omokagebito",
		eng: "sourudo-ru",
		validInputs: ["omokagebito", "omocagebito"],
		validInputs2: ["sourudo-ru"]
	},
	{
		kanji: "<Ruby>魂呼ばい<rt>たまよばい</rt></Ruby>",
		romaji: "tamayobai",
		eng: "tamayobai",
		validInputs: ["tamayobai"],
		validInputs2: ["tamayobai"]
	},
	{
		kanji: "<Ruby>人形受胎<rt>ドールキャッチャー</rt></Ruby>",
		romaji: "ningyoujutai",
		eng: "do-rukyattya-",
		validInputs: [
			"ningyoujutai",
			"ningyoujyutai",
			"ningyouzyutai",
			"ninngyoujutai",
			"ninngyoujyutai",
			"ninngyouzyutai"
		],
		validInputs2: ["do-rukyattya-", "do-rukyaccha-", "do-rukyaccya-"]
	},
	{
		kanji: "<Ruby>死亡遊戯<rt>ダツ デ ダーツ</rt></Ruby>",
		romaji: "sibouyuugi",
		eng: "datudeda-tu",
		validInputs: ["sibouyuugi", "shibouyuugi", "cibouyuugi"],
		validInputs2: ["datudeda-tu", "datudeda-tsu", "datsudeda-tu", "datsudeda-tsu"]
	},
	{
		kanji: "<Ruby>百万回生きた猫<rt>ねこのなまえ</rt></Ruby>",
		romaji: "hyakumankaiikitaneko",
		eng: "nekononamae",
		validInputs: [
			"hyakumankaiikitaneko",
			"hyakumankaiikitaneco",
			"hyakumancaiikitaneko",
			"hyakumancaiikitaneco",
			"hyacumankaiikitaneko",
			"hyacumankaiikitaneco",
			"hyacumancaiikitaneko",
			"hyacumancaiikitaneco",
			"hyaqumankaiikitaneko",
			"hyaqumankaiikitaneco",
			"hyaqumancaiikitaneko",
			"hyaqumancaiikitaneco",
			"hyakumannkaiikitaneko",
			"hyakumannkaiikitaneco",
			"hyakumanncaiikitaneko",
			"hyakumanncaiikitaneco",
			"hyacumannkaiikitaneko",
			"hyacumannkaiikitaneco",
			"hyacumanncaiikitaneko",
			"hyacumanncaiikitaneco",
			"hyaqumannkaiikitaneko",
			"hyaqumannkaiikitaneco",
			"hyaqumanncaiikitaneko",
			"hyaqumanncaiikitaneco"
		],
		validInputs2: ["nekononamae", "necononamae"]
	},
	{
		kanji: "<Ruby>気狂いピエロ<rt>クレイジースロット</rt></Ruby>",
		romaji: "kiguruipiero",
		eng: "kureiji-surotto",
		validInputs: ["kiguruipiero"],
		validInputs2: [
			"kureiji-surotto",
			"kureizi-surotto",
			"cureiji-surotto",
			"cureizi-surotto",
			"qureiji-surotto",
			"qureizi-surotto"
		]
	},
	{
		kanji: "<Ruby>死神の円舞曲<rt>サイレントワルツ</rt></Ruby>",
		romaji: "sinigaminoenbukyoku",
		eng: "sairentowarutu",
		validInputs: [
			"sinigaminoenbukyoku",
			"sinigaminoenbukyocu",
			"sinigaminoenbukyoqu",
			"shinigaminoenbukyoku",
			"shinigaminoenbukyocu",
			"shinigaminoenbukyoqu",
			"cinigaminoenbukyoku",
			"cinigaminoenbukyocu",
			"cinigaminoenbukyoqu",
			"sinigaminoennbukyoku",
			"sinigaminoennbukyocu",
			"sinigaminoennbukyoqu",
			"shinigaminoennbukyoku",
			"shinigaminoennbukyocu",
			"shinigaminoennbukyoqu",
			"cinigaminoennbukyoku",
			"cinigaminoennbukyocu",
			"cinigaminoennbukyoqu"
		],
		validInputs2: ["sairentowarutu", "sairentowarutsu"]
	},
	{
		kanji: "<Ruby>踊る気儘な火人形<rt>ダンシングドール</rt></Ruby>",
		romaji: "odorukimamanahiningyou",
		eng: "dansingudo-ru",
		validInputs: ["odorukimamanahiningyou", "odorukimamanahininngyou"],
		validInputs2: [
			"dansingudo-ru",
			"dansinngudo-ru",
			"dannsingudo-ru",
			"dannsinngudo-ru",
			"danshingudo-ru",
			"danshinngudo-ru",
			"dannshingudo-ru",
			"dannshinngudo-ru",
			"dancingudo-ru",
			"dancinngudo-ru",
			"danncingudo-ru",
			"danncinngudo-ru"
		]
	},
	{
		kanji: "<Ruby>虎咬真拳<rt>ここうしんけん</rt></Ruby>",
		romaji: "kokousinken",
		eng: "kokousinken",
		validInputs: [
			"kokousinken",
			"kokousinnken",
			"kokoushinken",
			"kokoushinnken",
			"kokoucinken",
			"kokoucinnken",
			"kocousinken",
			"kocousinnken",
			"kocoushinken",
			"kocoushinnken",
			"kocoucinken",
			"kocoucinnken",
			"cokousinken",
			"cokousinnken",
			"cokoushinken",
			"cokoushinnken",
			"cokoucinken",
			"cokoucinnken",
			"cocousinken",
			"cocousinnken",
			"cocoushinken",
			"cocoushinnken",
			"cocoucinken",
			"cocoucinnken"
		],
		validInputs2: [
			"kokousinken",
			"kokousinnken",
			"kokoushinken",
			"kokoushinnken",
			"kokoucinken",
			"kokoucinnken",
			"kocousinken",
			"kocousinnken",
			"kocoushinken",
			"kocoushinnken",
			"kocoucinken",
			"kocoucinnken",
			"cokousinken",
			"cokousinnken",
			"cokoushinken",
			"cokoushinnken",
			"cokoucinken",
			"cokoucinnken",
			"cocousinken",
			"cocousinnken",
			"cocoushinken",
			"cocoushinnken",
			"cocoucinken",
			"cocoucinnken"
		]
	},
	{
		kanji: "<Ruby>二人セゾン<rt>きみがいない</rt></Ruby>",
		romaji: "hutarisezon",
		eng: "kimigainai",
		validInputs: ["hutarisezon", "futarisezon"],
		validInputs2: ["kimigainai"]
	},
	{
		kanji: "<Ruby>蛇咬の舞<rt>だこうのまい</rt></Ruby>",
		romaji: "dakounomai",
		eng: "dakounomai",
		validInputs: ["dakounomai", "dacounomai"],
		validInputs2: ["dakounomai", "dacounomai"]
	},
	{
		kanji: "<Ruby>散弾独楽哀歌<rt>ショットガンブルース</rt></Ruby>",
		romaji: "sandangomaaika",
		eng: "syottoganburu-su",
		validInputs: [
			"sandangomaaika",
			"sandangomaaica",
			"sandanngomaaika",
			"sandanngomaaica",
			"sanndangomaaika",
			"sanndangomaaica",
			"sanndanngomaaika",
			"sanndanngomaaica"
		],
		validInputs2: ["syottoganburu-su", "shottoganburu-su", "syottogannburu-su", "shottogannburu-su"]
	},
	{
		kanji: "<Ruby>戦闘舞踏曲<rt>たたかいのワルツ</rt></Ruby>",
		romaji: "sentoubutoukyoku",
		eng: "tatakainowarutu",
		validInputs: [
			"sentoubutoukyoku",
			"sentoubutoukyocu",
			"sentoubutoukyoqu",
			"senntoubutoukyoku",
			"senntoubutoukyocu",
			"senntoubutoukyoqu"
		],
		validInputs2: ["tatakainowarutu", "tatakainowarutsu", "tatacainowarutu", "tatacainowarutsu"]
	},
	{
		kanji: "<Ruby>竜巻独楽<rt>たつまきごま</rt></Ruby>",
		romaji: "tatumakigoma",
		eng: "tatumakigoma",
		validInputs: ["tatumakigoma", "tatsumakigoma"],
		validInputs2: ["tatumakigoma", "tatsumakigoma"]
	},
	{
		kanji: "<Ruby>超不協輪怨<rt>シークレットノイズ</rt></Ruby>",
		romaji: "tyouhukyouwaon",
		eng: "si-kurettonoizu",
		validInputs: [
			"tyouhukyouwaon",
			"tyoufukyouwaon",
			"cyouhukyouwaon",
			"cyoufukyouwaon",
			"chouhukyouwaon",
			"choufukyouwaon"
		],
		validInputs2: [
			"si-kurettonoizu",
			"si-curettonoizu",
			"si-qurettonoizu",
			"shi-kurettonoizu",
			"shi-curettonoizu",
			"shi-qurettonoizu",
			"ci-kurettonoizu",
			"ci-curettonoizu",
			"ci-qurettonoizu"
		]
	},
	{
		kanji: "<Ruby>雷掌<rt>イズツシ</rt></Ruby>",
		romaji: "raisyou",
		eng: "izutusi",
		validInputs: ["raisyou", "raishou"],
		validInputs2: ["izutusi", "izutushi", "izutuci", "izutsusi", "izutsushi", "izutsuci"]
	},
	{
		kanji: "<Ruby>神速<rt>カンムル</rt></Ruby>",
		romaji: "sinsoku",
		eng: "kanmuru",
		validInputs: [
			"sinsoku",
			"sinsocu",
			"sinsoqu",
			"shinsoku",
			"shinsocu",
			"shinsoqu",
			"cinsoku",
			"cinsocu",
			"cinsoqu",
			"sinnsoku",
			"sinnsocu",
			"sinnsoqu",
			"shinnsoku",
			"shinnsocu",
			"shinnsoqu",
			"cinnsoku",
			"cinnsocu",
			"cinnsoqu"
		],
		validInputs2: ["kanmuru", "canmuru", "kannmuru", "cannmuru"]
	},
	{
		kanji: "<Ruby>落雷<rt>ナルカミ</rt></Ruby>",
		romaji: "rakurai",
		eng: "narukami",
		validInputs: ["rakurai", "racurai", "raqurai"],
		validInputs2: ["narukami", "narucami"]
	},
	{
		kanji: "<Ruby>絶対時間<rt>エンペラータイム</rt></Ruby>",
		romaji: "zettaijikan",
		eng: "ennpera-taimu",
		validInputs: ["zettaijikan", "zettaijican", "zettaizikan", "zettaizican"],
		validInputs2: ["enpera-taimu", "ennpera-taimu"]
	},
	{
		kanji: "<Ruby>律する小指の鎖<rt>ジャッジメントチェーン</rt></Ruby>",
		romaji: "rissurukoyubinokusari",
		eng: "jajjimentotye-n",
		validInputs: [
			"rissurukoyubinokusari",
			"rissurukoyubinocusari",
			"rissurukoyubinoqusari",
			"rissurucoyubinokusari",
			"rissurucoyubinocusari",
			"rissurucoyubinoqusari"
		],
		validInputs2: [
			"jajjimentotye-n",
			"jajjimentocye-n",
			"jajjimentoche-n",
			"jazzimentotye-n",
			"jazzimentocye-n",
			"jazzimentoche-n",
			"jyajjimentotye-n",
			"jyajjimentocye-n",
			"jyajjimentoche-n",
			"jyazzimentotye-n",
			"jyazzimentocye-n",
			"jyazzimentoche-n",
			"zyajjimentotye-n",
			"zyajjimentocye-n",
			"zyajjimentoche-n",
			"zyazzimentotye-n",
			"zyazzimentocye-n",
			"zyazzimentoche-n",
			"jajjimenntotye-n",
			"jajjimenntocye-n",
			"jajjimenntoche-n",
			"jazzimenntotye-n",
			"jazzimenntocye-n",
			"jazzimenntoche-n",
			"jyajjimenntotye-n",
			"jyajjimenntocye-n",
			"jyajjimenntoche-n",
			"jyazzimenntotye-n",
			"jyazzimenntocye-n",
			"jyazzimenntoche-n",
			"zyajjimenntotye-n",
			"zyajjimenntocye-n",
			"zyajjimenntoche-n",
			"zyazzimenntotye-n",
			"zyazzimenntocye-n",
			"zyazzimenntoche-n"
		]
	},
	{
		kanji: "<Ruby>奪う人差し指の鎖<rt>スチールチェーン</rt></Ruby>",
		romaji: "ubauhitosasiyubinokusari",
		eng: "suti-rutye-n",
		validInputs: [
			"ubauhitosasiyubinokusari",
			"ubauhitosasiyubinocusari",
			"ubauhitosasiyubinoqusari",
			"ubauhitosashiyubinokusari",
			"ubauhitosashiyubinocusari",
			"ubauhitosashiyubinoqusari",
			"ubauhitosaciyubinokusari",
			"ubauhitosaciyubinocusari",
			"ubauhitosaciyubinoqusari"
		],
		validInputs2: ["suti-rutye-n", "suti-rucye-n", "suti-ruche-n", "suchi-rutye-n", "suchi-rucye-n", "suchi-ruche-n"]
	},
	{
		kanji: "<Ruby>導く薬指の鎖<rt>ダウジングチェーン</rt></Ruby>",
		romaji: "mitibikukusuriyubinokusari",
		eng: "daujingutye-n",
		validInputs: [
			"mitibikukusuriyubinokusari",
			"mitibikukusuriyubinocusari",
			"mitibikukusuriyubinoqusari",
			"mitibikucusuriyubinokusari",
			"mitibikucusuriyubinocusari",
			"mitibikucusuriyubinoqusari",
			"mitibikuqusuriyubinokusari",
			"mitibikuqusuriyubinocusari",
			"mitibikuqusuriyubinoqusari",
			"mitibicukusuriyubinokusari",
			"mitibicukusuriyubinocusari",
			"mitibicukusuriyubinoqusari",
			"mitibicucusuriyubinokusari",
			"mitibicucusuriyubinocusari",
			"mitibicucusuriyubinoqusari",
			"mitibicuqusuriyubinokusari",
			"mitibicuqusuriyubinocusari",
			"mitibicuqusuriyubinoqusari",
			"mitibiqukusuriyubinokusari",
			"mitibiqukusuriyubinocusari",
			"mitibiqukusuriyubinoqusari",
			"mitibiqucusuriyubinokusari",
			"mitibiqucusuriyubinocusari",
			"mitibiqucusuriyubinoqusari",
			"mitibiququsuriyubinokusari",
			"mitibiququsuriyubinocusari",
			"mitibiququsuriyubinoqusari",
			"michibikukusuriyubinokusari",
			"michibikukusuriyubinocusari",
			"michibikukusuriyubinoqusari",
			"michibikucusuriyubinokusari",
			"michibikucusuriyubinocusari",
			"michibikucusuriyubinoqusari",
			"michibikuqusuriyubinokusari",
			"michibikuqusuriyubinocusari",
			"michibikuqusuriyubinoqusari",
			"michibicukusuriyubinokusari",
			"michibicukusuriyubinocusari",
			"michibicukusuriyubinoqusari",
			"michibicucusuriyubinokusari",
			"michibicucusuriyubinocusari",
			"michibicucusuriyubinoqusari",
			"michibicuqusuriyubinokusari",
			"michibicuqusuriyubinocusari",
			"michibicuqusuriyubinoqusari",
			"michibiqukusuriyubinokusari",
			"michibiqukusuriyubinocusari",
			"michibiqukusuriyubinoqusari",
			"michibiqucusuriyubinokusari",
			"michibiqucusuriyubinocusari",
			"michibiqucusuriyubinoqusari",
			"michibiququsuriyubinokusari",
			"michibiququsuriyubinocusari",
			"michibiququsuriyubinoqusari"
		],
		validInputs2: [
			"daujingutye-n",
			"daujingucye-n",
			"daujinguche-n",
			"dauzingutye-n",
			"dauzingucye-n",
			"dauzinguche-n",
			"daujinngutye-n",
			"daujinngucye-n",
			"daujinnguche-n",
			"dauzinngutye-n",
			"dauzinngucye-n",
			"dauzinnguche-n"
		]
	},
	{
		kanji: "<Ruby>束縛する中指の鎖<rt>チェーンジェイル</rt></Ruby>",
		romaji: "sokubakusurunakayubinokusari",
		eng: "tye-njeiru",
		validInputs: [
			"sokubakusurunakayubinokusari",
			"sokubakusurunakayubinocusari",
			"sokubakusurunakayubinoqusari",
			"sokubakusurunacayubinokusari",
			"sokubakusurunacayubinocusari",
			"sokubakusurunacayubinoqusari",
			"sokubacusurunakayubinokusari",
			"sokubacusurunakayubinocusari",
			"sokubacusurunakayubinoqusari",
			"sokubacusurunacayubinokusari",
			"sokubacusurunacayubinocusari",
			"sokubacusurunacayubinoqusari",
			"sokubaqusurunakayubinokusari",
			"sokubaqusurunakayubinocusari",
			"sokubaqusurunakayubinoqusari",
			"sokubaqusurunacayubinokusari",
			"sokubaqusurunacayubinocusari",
			"sokubaqusurunacayubinoqusari",
			"socubakusurunakayubinokusari",
			"socubakusurunakayubinocusari",
			"socubakusurunakayubinoqusari",
			"socubakusurunacayubinokusari",
			"socubakusurunacayubinocusari",
			"socubakusurunacayubinoqusari",
			"socubacusurunakayubinokusari",
			"socubacusurunakayubinocusari",
			"socubacusurunakayubinoqusari",
			"socubacusurunacayubinokusari",
			"socubacusurunacayubinocusari",
			"socubacusurunacayubinoqusari",
			"socubaqusurunakayubinokusari",
			"socubaqusurunakayubinocusari",
			"socubaqusurunakayubinoqusari",
			"socubaqusurunacayubinokusari",
			"socubaqusurunacayubinocusari",
			"socubaqusurunacayubinoqusari",
			"soqubakusurunakayubinokusari",
			"soqubakusurunakayubinocusari",
			"soqubakusurunakayubinoqusari",
			"soqubakusurunacayubinokusari",
			"soqubakusurunacayubinocusari",
			"soqubakusurunacayubinoqusari",
			"soqubacusurunakayubinokusari",
			"soqubacusurunakayubinocusari",
			"soqubacusurunakayubinoqusari",
			"soqubacusurunacayubinokusari",
			"soqubacusurunacayubinocusari",
			"soqubacusurunacayubinoqusari",
			"soqubaqusurunakayubinokusari",
			"soqubaqusurunakayubinocusari",
			"soqubaqusurunakayubinoqusari",
			"soqubaqusurunacayubinokusari",
			"soqubaqusurunacayubinocusari",
			"soqubaqusurunacayubinoqusari"
		],
		validInputs2: [
			"tye-njeiru",
			"tye-njyeiru",
			"tye-nzyeiru",
			"cye-njeiru",
			"cye-njyeiru",
			"cye-nzyeiru",
			"che-njeiru",
			"che-njyeiru",
			"che-nzyeiru",
			"tye-nnjeiru",
			"tye-nnjyeiru",
			"tye-nnzyeiru",
			"cye-nnjeiru",
			"cye-nnjyeiru",
			"cye-nnzyeiru",
			"che-nnjeiru",
			"che-nnjyeiru",
			"che-nnzyeiru"
		]
	},
	{
		kanji: "<Ruby>癒す親指の鎖<rt>ホーリーチェーン</rt></Ruby>",
		romaji: "iyasuoyayubinokusari",
		eng: "ho-ri-tye-n",
		validInputs: ["iyasuoyayubinokusari", "iyasuoyayubinocusari", "iyasuoyayubinoqusari"],
		validInputs2: ["ho-ri-tye-n", "ho-ri-cye-n", "ho-ri-che-n"]
	},
	{
		kanji: "<Ruby>密室遊魚<rt>インドアフィッシュ</rt></Ruby>",
		romaji: "missituyuugyo",
		eng: "indoafissyu",
		validInputs: [
			"missituyuugyo",
			"missitsuyuugyo",
			"misshituyuugyo",
			"misshitsuyuugyo",
			"miccituyuugyo",
			"miccitsuyuugyo"
		],
		validInputs2: ["indoafissyu", "indoafisshu", "inndoafissyu", "inndoafisshu"]
	},
	{
		kanji: "<Ruby>人間の証明<rt>オーダースタンプ</rt></Ruby>",
		romaji: "ningennnosyoumei",
		eng: "o-da-sutanpu",
		validInputs: ["ningennnosyoumei", "ningennnoshoumei"],
		validInputs2: ["o-da-sutanpu", "o-da-sutannpu"]
	},
	{
		kanji: "<Ruby>転校生<rt>コンバートハンズ</rt></Ruby>",
		romaji: "tenkousei",
		eng: "konba-tohanzu",
		validInputs: ["tenkousei", "tencousei", "tennkousei", "tenncousei"],
		validInputs2: [
			"konba-tohanzu",
			"conba-tohanzu",
			"konba-tohannzu",
			"conba-tohannzu",
			"konnba-tohanzu",
			"connba-tohanzu",
			"konnba-tohannzu",
			"connba-tohannzu"
		]
	},
	{
		kanji: "<Ruby>番いの破壊者<rt>サンアンドムーン</rt></Ruby>",
		romaji: "tugainohakaisya",
		eng: "sannandomu-n",
		validInputs: [
			"tugainohakaisya",
			"tugainohakaisha",
			"tugainohacaisya",
			"tugainohacaisha",
			"tsugainohakaisya",
			"tsugainohakaisha",
			"tsugainohacaisya",
			"tsugainohacaisha"
		],
		validInputs2: ["sannandomu-n"]
	},
	{
		kanji: "<Ruby>盗賊の極意<rt>スキルハンター</rt></Ruby>",
		romaji: "touzokunogokui",
		eng: "sukiruhanta-",
		validInputs: [
			"touzokunogokui",
			"touzokunogocui",
			"touzokunogoqui",
			"touzocunogokui",
			"touzocunogocui",
			"touzocunogoqui",
			"touzoqunogokui",
			"touzoqunogocui",
			"touzoqunogoqui"
		],
		validInputs2: ["sukiruhanta-", "sukiruhannta-"]
	},
	{
		kanji: "<Ruby>栞のテーマ<rt>ダブルフェイス</rt></Ruby>",
		romaji: "siorinote-ma",
		eng: "daburufeisu",
		validInputs: ["siorinote-ma", "shiorinote-ma", "ciorinote-ma"],
		validInputs2: ["daburufeisu"]
	},
	{
		kanji: "<Ruby>一握りの火薬<rt>リトルフラワー</rt></Ruby>",
		romaji: "hitonigirinokayaku",
		eng: "ritorufurawa-",
		validInputs: [
			"hitonigirinokayaku",
			"hitonigirinokayacu",
			"hitonigirinokayaqu",
			"hitonigirinocayaku",
			"hitonigirinocayacu",
			"hitonigirinocayaqu"
		],
		validInputs2: ["ritorufurawa-", "ritoruhurawa-"]
	},
	{
		kanji: "<Ruby>神の左手悪魔の右手<rt>ギャラリーフェイク</rt></Ruby>",
		romaji: "kaminohidariteakumanomigite",
		eng: "gyarari-feiku",
		validInputs: [
			"kaminohidariteakumanomigite",
			"kaminohidariteacumanomigite",
			"kaminohidariteaqumanomigite",
			"caminohidariteakumanomigite",
			"caminohidariteacumanomigite",
			"caminohidariteaqumanomigite"
		],
		validInputs2: ["gyarari-feiku", "gyarari-feicu", "gyarari-feiqu"]
	},
	{
		kanji: "<Ruby>黒い賢人<rt>ブラックゴレイヌ</rt></Ruby>",
		romaji: "kuroikenjin",
		eng: "burakkugoreinu",
		validInputs: [
			"kuroikenjin",
			"kuroikenzin",
			"curoikenjin",
			"curoikenzin",
			"quroikenjin",
			"quroikenzin",
			"kuroikennjin",
			"kuroikennzin",
			"curoikennjin",
			"curoikennzin",
			"quroikennjin",
			"quroikennzin"
		],
		validInputs2: ["burakkugoreinu", "buraccugoreinu", "buraqqugoreinu"]
	},
	{
		kanji: "<Ruby>白い賢人<rt>ホワイトゴレイヌ</rt></Ruby>",
		romaji: "siroikenjin",
		eng: "howaitogoreinu",
		validInputs: [
			"siroikenjin",
			"siroikenzin",
			"shiroikenjin",
			"shiroikenzin",
			"ciroikenjin",
			"ciroikenzin",
			"siroikennjin",
			"siroikennzin",
			"shiroikennjin",
			"shiroikennzin",
			"ciroikennjin",
			"ciroikennzin"
		],
		validInputs2: ["howaitogoreinu"]
	},
	{
		kanji: "<Ruby>ジャジャン拳<rt>ジャジャンケン</rt></Ruby>",
		romaji: "jajanken",
		eng: "jajanken",
		validInputs: [
			"jajanken",
			"jajyanken",
			"jazyanken",
			"jyajanken",
			"jyajyanken",
			"jyazyanken",
			"zyajanken",
			"zyajyanken",
			"zyazyanken",
			"jajannken",
			"jajyannken",
			"jazyannken",
			"jyajannken",
			"jyajyannken",
			"jyazyannken",
			"zyajannken",
			"zyajyannken",
			"zyazyannken"
		],
		validInputs2: [
			"jajanken",
			"jajyanken",
			"jazyanken",
			"jyajanken",
			"jyajyanken",
			"jyazyanken",
			"zyajanken",
			"zyajyanken",
			"zyazyanken",
			"jajannken",
			"jajyannken",
			"jazyannken",
			"jyajannken",
			"jyajyannken",
			"jyazyannken",
			"zyajannken",
			"zyajyannken",
			"zyazyannken"
		]
	},
	{
		kanji: "<Ruby>血いさな世界<rt>ブラッディメアリー</rt></Ruby>",
		romaji: "tiisanasekai",
		eng: "buraddhimeari-",
		validInputs: ["tiisanasekai", "tiisanasecai", "chiisanasekai", "chiisanasecai"],
		validInputs2: ["buraddhimeari-", "buraddelimeari-", "buraddeximeari-"]
	},
	{
		kanji: "<Ruby>審美的転生注射<rt>クイーンショット</rt></Ruby>",
		romaji: "sinbitekitenseityuusya",
		eng: "kui-nsyotto",
		validInputs: [
			"sinbitekitenseityuusya",
			"sinbitekitenseityuusha",
			"sinbitekitenseicyuusya",
			"sinbitekitenseicyuusha",
			"sinbitekitenseichuusya",
			"sinbitekitenseichuusha",
			"shinbitekitenseityuusya",
			"shinbitekitenseityuusha",
			"shinbitekitenseicyuusya",
			"shinbitekitenseicyuusha",
			"shinbitekitenseichuusya",
			"shinbitekitenseichuusha",
			"cinbitekitenseityuusya",
			"cinbitekitenseityuusha",
			"cinbitekitenseicyuusya",
			"cinbitekitenseicyuusha",
			"cinbitekitenseichuusya",
			"cinbitekitenseichuusha",
			"sinbitekitennseityuusya",
			"sinbitekitennseityuusha",
			"sinbitekitennseicyuusya",
			"sinbitekitennseicyuusha",
			"sinbitekitennseichuusya",
			"sinbitekitennseichuusha",
			"shinbitekitennseityuusya",
			"shinbitekitennseityuusha",
			"shinbitekitennseicyuusya",
			"shinbitekitennseicyuusha",
			"shinbitekitennseichuusya",
			"shinbitekitennseichuusha",
			"cinbitekitennseityuusya",
			"cinbitekitennseityuusha",
			"cinbitekitennseicyuusya",
			"cinbitekitennseicyuusha",
			"cinbitekitennseichuusya",
			"cinbitekitennseichuusha",
			"sinnbitekitenseityuusya",
			"sinnbitekitenseityuusha",
			"sinnbitekitenseicyuusya",
			"sinnbitekitenseicyuusha",
			"sinnbitekitenseichuusya",
			"sinnbitekitenseichuusha",
			"shinnbitekitenseityuusya",
			"shinnbitekitenseityuusha",
			"shinnbitekitenseicyuusya",
			"shinnbitekitenseicyuusha",
			"shinnbitekitenseichuusya",
			"shinnbitekitenseichuusha",
			"cinnbitekitenseityuusya",
			"cinnbitekitenseityuusha",
			"cinnbitekitenseicyuusya",
			"cinnbitekitenseicyuusha",
			"cinnbitekitenseichuusya",
			"cinnbitekitenseichuusha",
			"sinnbitekitennseityuusya",
			"sinnbitekitennseityuusha",
			"sinnbitekitennseicyuusya",
			"sinnbitekitennseicyuusha",
			"sinnbitekitennseichuusya",
			"sinnbitekitennseichuusha",
			"shinnbitekitennseityuusya",
			"shinnbitekitennseityuusha",
			"shinnbitekitennseicyuusya",
			"shinnbitekitennseicyuusha",
			"shinnbitekitennseichuusya",
			"shinnbitekitennseichuusha",
			"cinnbitekitennseityuusya",
			"cinnbitekitennseityuusha",
			"cinnbitekitennseicyuusya",
			"cinnbitekitennseicyuusha",
			"cinnbitekitennseichuusya",
			"cinnbitekitennseichuusha"
		],
		validInputs2: [
			"kui-nsyotto",
			"kui-nshotto",
			"cui-nsyotto",
			"cui-nshotto",
			"qui-nsyotto",
			"qui-nshotto",
			"kui-nnsyotto",
			"kui-nnshotto",
			"cui-nnsyotto",
			"cui-nnshotto",
			"qui-nnsyotto",
			"qui-nnshotto"
		]
	},
	{
		kanji: "<Ruby>遊戯王<rt>カルドセプト</rt></Ruby>",
		romaji: "yuugiou",
		eng: "karudoseputo",
		validInputs: ["yuugiou"],
		validInputs2: ["karudoseputo", "carudoseputo"]
	},
	{
		kanji: "<Ruby>デメちゃん<rt>でめちゃん</rt></Ruby>",
		romaji: "demetyan",
		eng: "demetyan",
		validInputs: ["demetyan", "demecyan", "demechan"],
		validInputs2: ["demetyan", "demecyan", "demechan"]
	},
	{
		kanji: "<Ruby>大和撫子七変化<rt>ライダーズハイ</rt></Ruby>",
		romaji: "yamatonadesikositihenge",
		eng: "raida-zuhai",
		validInputs: [
			"yamatonadesikositihenge",
			"yamatonadesikosichihenge",
			"yamatonadesikoshitihenge",
			"yamatonadesikoshichihenge",
			"yamatonadesikocitihenge",
			"yamatonadesikocichihenge",
			"yamatonadesicositihenge",
			"yamatonadesicosichihenge",
			"yamatonadesicoshitihenge",
			"yamatonadesicoshichihenge",
			"yamatonadesicocitihenge",
			"yamatonadesicocichihenge",
			"yamatonadeshikositihenge",
			"yamatonadeshikosichihenge",
			"yamatonadeshikoshitihenge",
			"yamatonadeshikoshichihenge",
			"yamatonadeshikocitihenge",
			"yamatonadeshikocichihenge",
			"yamatonadeshicositihenge",
			"yamatonadeshicosichihenge",
			"yamatonadeshicoshitihenge",
			"yamatonadeshicoshichihenge",
			"yamatonadeshicocitihenge",
			"yamatonadeshicocichihenge",
			"yamatonadecikositihenge",
			"yamatonadecikosichihenge",
			"yamatonadecikoshitihenge",
			"yamatonadecikoshichihenge",
			"yamatonadecikocitihenge",
			"yamatonadecikocichihenge",
			"yamatonadecicositihenge",
			"yamatonadecicosichihenge",
			"yamatonadecicoshitihenge",
			"yamatonadecicoshichihenge",
			"yamatonadecicocitihenge",
			"yamatonadecicocichihenge",
			"yamatonadesikositihennge",
			"yamatonadesikosichihennge",
			"yamatonadesikoshitihennge",
			"yamatonadesikoshichihennge",
			"yamatonadesikocitihennge",
			"yamatonadesikocichihennge",
			"yamatonadesicositihennge",
			"yamatonadesicosichihennge",
			"yamatonadesicoshitihennge",
			"yamatonadesicoshichihennge",
			"yamatonadesicocitihennge",
			"yamatonadesicocichihennge",
			"yamatonadeshikositihennge",
			"yamatonadeshikosichihennge",
			"yamatonadeshikoshitihennge",
			"yamatonadeshikoshichihennge",
			"yamatonadeshikocitihennge",
			"yamatonadeshikocichihennge",
			"yamatonadeshicositihennge",
			"yamatonadeshicosichihennge",
			"yamatonadeshicoshitihennge",
			"yamatonadeshicoshichihennge",
			"yamatonadeshicocitihennge",
			"yamatonadeshicocichihennge",
			"yamatonadecikositihennge",
			"yamatonadecikosichihennge",
			"yamatonadecikoshitihennge",
			"yamatonadecikoshichihennge",
			"yamatonadecikocitihennge",
			"yamatonadecikocichihennge",
			"yamatonadecicositihennge",
			"yamatonadecicosichihennge",
			"yamatonadecicoshitihennge",
			"yamatonadecicoshichihennge",
			"yamatonadecicocitihennge",
			"yamatonadecicocichihennge"
		],
		validInputs2: ["raida-zuhai"]
	},
	{
		kanji: "<Ruby>麟粉乃愛泉<rt>スピリチュアルメッセージ</rt></Ruby>",
		romaji: "rinpunnnoai",
		eng: "supirityuarumesse-ji",
		validInputs: ["rinpunnnoai", "rinnpunnnoai"],
		validInputs2: [
			"supirityuarumesse-ji",
			"supirityuarumesse-zi",
			"supiricyuarumesse-ji",
			"supiricyuarumesse-zi",
			"supirichuarumesse-ji",
			"supirichuarumesse-zi"
		]
	},
	{
		kanji: "<Ruby>蠅の王<rt>ベルゼブブ</rt></Ruby>",
		romaji: "haenoou",
		eng: "beruzebubu",
		validInputs: ["haenoou"],
		validInputs2: ["beruzebubu"]
	},
	{
		kanji: "<Ruby>縁の下の11人<rt>イレブンブラックチルドレン</rt></Ruby>",
		romaji: "ennnositano11nin",
		eng: "irebunburakkutirudoren",
		validInputs: ["ennnositano11nin", "ennnoshitano11nin", "ennnocitano11nin"],
		validInputs2: [
			"irebunburakkutirudoren",
			"irebunburakkuchirudoren",
			"irebunburaccutirudoren",
			"irebunburaccuchirudoren",
			"irebunburaqqutirudoren",
			"irebunburaqquchirudoren",
			"irebunnburakkutirudoren",
			"irebunnburakkuchirudoren",
			"irebunnburaccutirudoren",
			"irebunnburaccuchirudoren",
			"irebunnburaqqutirudoren",
			"irebunnburaqquchirudoren"
		]
	},
	{
		kanji: "<Ruby>携帯する他人の運命<rt>ブラックボイス</rt></Ruby>",
		romaji: "keitaisurutaninnnounmei",
		eng: "burakkuboisu",
		validInputs: ["keitaisurutaninnnounmei"],
		validInputs2: ["burakkuboisu", "buraccuboisu", "buraqquboisu"]
	},
	{
		kanji: "<Ruby>暗い宿<rt>ホテルラフレシア</rt></Ruby>",
		romaji: "kuraiyado",
		eng: "hoterurahuresia",
		validInputs: ["kuraiyado", "curaiyado", "quraiyado"],
		validInputs2: [
			"hoterurahuresia",
			"hoterurahureshia",
			"hoterurahurecia",
			"hoterurafuresia",
			"hoterurafureshia",
			"hoterurafurecia"
		]
	},
	{
		kanji: "<Ruby>物真似鳥<rt>ジェイプシフター</rt></Ruby>",
		romaji: "monomanedori",
		eng: "jeipusihuta-",
		validInputs: ["monomanedori"],
		validInputs2: [
			"jeipusihuta-",
			"jeipusifuta-",
			"jeipushihuta-",
			"jeipushifuta-",
			"jeipucihuta-",
			"jeipucifuta-",
			"jyeipusihuta-",
			"jyeipusifuta-",
			"jyeipushihuta-",
			"jyeipushifuta-",
			"jyeipucihuta-",
			"jyeipucifuta-",
			"zyeipusihuta-",
			"zyeipusifuta-",
			"zyeipushihuta-",
			"zyeipushifuta-",
			"zyeipucihuta-",
			"zyeipucifuta-"
		]
	},
	{
		kanji: "<Ruby>機械に巣食う棘<rt>マシンイーター</rt></Ruby>",
		romaji: "kikainisukuutoge",
		eng: "masinni-ta-",
		validInputs: [
			"kikainisukuutoge",
			"kikainisucuutoge",
			"kikainisuquutoge",
			"kicainisukuutoge",
			"kicainisucuutoge",
			"kicainisuquutoge"
		],
		validInputs2: ["masinni-ta-", "mashinni-ta-", "macinni-ta-"]
	},
	{
		kanji: "<Ruby>龍星群<rt>ドラゴンダイヴ</rt></Ruby>",
		romaji: "ryuuseigun",
		eng: "doragondaivu",
		validInputs: ["ryuuseigun"],
		validInputs2: ["doragondaivu", "doragonndaivu"]
	},
	{
		kanji: "<Ruby>龍頭戯画<rt>ドラゴンヘッド</rt></Ruby>",
		romaji: "ryuutougiga",
		eng: "doragonheddo",
		validInputs: ["ryuutougiga"],
		validInputs2: ["doragonheddo", "doragonnheddo"]
	},
	{
		kanji: "<Ruby>牙突<rt>ドラゴンランス</rt></Ruby>",
		romaji: "gatotu",
		eng: "doragonransu",
		validInputs: ["gatotu", "gatotsu"],
		validInputs2: ["doragonransu", "doragonnransu"]
	},
	{
		kanji: "<Ruby>蠅の仕事<rt>サイレントワーカー</rt></Ruby>",
		romaji: "haenosigoto",
		eng: "sairentowa-ka-",
		validInputs: ["haenosigoto", "haenoshigoto", "haenocigoto"],
		validInputs2: ["sairentowa-ka-", "sairentowa-ca-", "sairenntowa-ka-", "sairenntowa-ca-"]
	},
	{
		kanji: "<Ruby>天上不知唯我独損<rt>ハコワレ</rt></Ruby>",
		romaji: "tenjouhutiyuigadokuson",
		eng: "hakoware",
		validInputs: [
			"tenjouhutiyuigadokuson",
			"tenjouhutiyuigadocuson",
			"tenjouhutiyuigadoquson",
			"tenjouhuchiyuigadokuson",
			"tenjouhuchiyuigadocuson",
			"tenjouhuchiyuigadoquson",
			"tenjoufutiyuigadokuson",
			"tenjoufutiyuigadocuson",
			"tenjoufutiyuigadoquson",
			"tenjoufuchiyuigadokuson",
			"tenjoufuchiyuigadocuson",
			"tenjoufuchiyuigadoquson",
			"tenjyouhutiyuigadokuson",
			"tenjyouhutiyuigadocuson",
			"tenjyouhutiyuigadoquson",
			"tenjyouhuchiyuigadokuson",
			"tenjyouhuchiyuigadocuson",
			"tenjyouhuchiyuigadoquson",
			"tenjyoufutiyuigadokuson",
			"tenjyoufutiyuigadocuson",
			"tenjyoufutiyuigadoquson",
			"tenjyoufuchiyuigadokuson",
			"tenjyoufuchiyuigadocuson",
			"tenjyoufuchiyuigadoquson",
			"tenzyouhutiyuigadokuson",
			"tenzyouhutiyuigadocuson",
			"tenzyouhutiyuigadoquson",
			"tenzyouhuchiyuigadokuson",
			"tenzyouhuchiyuigadocuson",
			"tenzyouhuchiyuigadoquson",
			"tenzyoufutiyuigadokuson",
			"tenzyoufutiyuigadocuson",
			"tenzyoufutiyuigadoquson",
			"tenzyoufuchiyuigadokuson",
			"tenzyoufuchiyuigadocuson",
			"tenzyoufuchiyuigadoquson",
			"tennjouhutiyuigadokuson",
			"tennjouhutiyuigadocuson",
			"tennjouhutiyuigadoquson",
			"tennjouhuchiyuigadokuson",
			"tennjouhuchiyuigadocuson",
			"tennjouhuchiyuigadoquson",
			"tennjoufutiyuigadokuson",
			"tennjoufutiyuigadocuson",
			"tennjoufutiyuigadoquson",
			"tennjoufuchiyuigadokuson",
			"tennjoufuchiyuigadocuson",
			"tennjoufuchiyuigadoquson",
			"tennjyouhutiyuigadokuson",
			"tennjyouhutiyuigadocuson",
			"tennjyouhutiyuigadoquson",
			"tennjyouhuchiyuigadokuson",
			"tennjyouhuchiyuigadocuson",
			"tennjyouhuchiyuigadoquson",
			"tennjyoufutiyuigadokuson",
			"tennjyoufutiyuigadocuson",
			"tennjyoufutiyuigadoquson",
			"tennjyoufuchiyuigadokuson",
			"tennjyoufuchiyuigadocuson",
			"tennjyoufuchiyuigadoquson",
			"tennzyouhutiyuigadokuson",
			"tennzyouhutiyuigadocuson",
			"tennzyouhutiyuigadoquson",
			"tennzyouhuchiyuigadokuson",
			"tennzyouhuchiyuigadocuson",
			"tennzyouhuchiyuigadoquson",
			"tennzyoufutiyuigadokuson",
			"tennzyoufutiyuigadocuson",
			"tennzyoufutiyuigadoquson",
			"tennzyoufuchiyuigadokuson",
			"tennzyoufuchiyuigadocuson",
			"tennzyoufuchiyuigadoquson"
		],
		validInputs2: ["hakoware", "hacoware"]
	},
	{
		kanji: "<Ruby>天使の自動筆記<rt>ラブリーゴーストライター</rt></Ruby>",
		romaji: "tensinojidouhikki",
		eng: "raburi-go-sutoraita-",
		validInputs: [
			"tensinojidouhikki",
			"tensinozidouhikki",
			"tenshinojidouhikki",
			"tenshinozidouhikki",
			"tencinojidouhikki",
			"tencinozidouhikki",
			"tennsinojidouhikki",
			"tennsinozidouhikki",
			"tennshinojidouhikki",
			"tennshinozidouhikki",
			"tenncinojidouhikki",
			"tenncinozidouhikki"
		],
		validInputs2: ["raburi-go-sutoraita-"]
	},
	{
		kanji: "<Ruby>黒子無想<rt>テレプシコーラ</rt></Ruby>",
		romaji: "kokusimusou",
		eng: "terepusiko-ra",
		validInputs: [
			"kokusimusou",
			"kokushimusou",
			"kokucimusou",
			"kocusimusou",
			"kocushimusou",
			"kocucimusou",
			"koqusimusou",
			"koqushimusou",
			"koqucimusou",
			"cokusimusou",
			"cokushimusou",
			"cokucimusou",
			"cocusimusou",
			"cocushimusou",
			"cocucimusou",
			"coqusimusou",
			"coqushimusou",
			"coqucimusou"
		],
		validInputs2: [
			"terepusiko-ra",
			"terepusico-ra",
			"terepushiko-ra",
			"terepushico-ra",
			"terepuciko-ra",
			"terepucico-ra"
		]
	},
	{
		kanji: "<Ruby>玩具修理者<rt>ドクターブライス</rt></Ruby>",
		romaji: "gangusyuurisya",
		eng: "dokuta-buraisu",
		validInputs: [
			"gangusyuurisya",
			"gangusyuurisha",
			"gangushuurisya",
			"gangushuurisha",
			"ganngusyuurisya",
			"ganngusyuurisha",
			"ganngushuurisya",
			"ganngushuurisha"
		],
		validInputs2: ["dokuta-buraisu", "docuta-buraisu", "doquta-buraisu"]
	},
	{
		kanji: "<Ruby>窓を開く者<rt>スクリーム</rt></Ruby>",
		romaji: "madowohirakumono",
		eng: "sukuri-mu",
		validInputs: ["madowohirakumono", "madowohiracumono", "madowohiraqumono"],
		validInputs2: ["sukuri-mu", "sucuri-mu", "suquri-mu"]
	},
	{
		kanji: "<Ruby>四次元マンション<rt>ハイドアンドシーク</rt></Ruby>",
		romaji: "yojigenmansyon",
		eng: "haidoandosi-ku",
		validInputs: [
			"yojigenmansyon",
			"yojigenmanshon",
			"yozigenmansyon",
			"yozigenmanshon",
			"yojigenmannsyon",
			"yojigenmannshon",
			"yozigenmannsyon",
			"yozigenmannshon",
			"yojigennmansyon",
			"yojigennmanshon",
			"yozigennmansyon",
			"yozigennmanshon",
			"yojigennmannsyon",
			"yojigennmannshon",
			"yozigennmannsyon",
			"yozigennmannshon"
		],
		validInputs2: [
			"haidoandosi-ku",
			"haidoandosi-cu",
			"haidoandosi-qu",
			"haidoandoshi-ku",
			"haidoandoshi-cu",
			"haidoandoshi-qu",
			"haidoandoci-ku",
			"haidoandoci-cu",
			"haidoandoci-qu",
			"haidoanndosi-ku",
			"haidoanndosi-cu",
			"haidoanndosi-qu",
			"haidoanndoshi-ku",
			"haidoanndoshi-cu",
			"haidoanndoshi-qu",
			"haidoanndoci-ku",
			"haidoanndoci-cu",
			"haidoanndoci-qu"
		]
	},
	{
		kanji: "<Ruby>淋しい深海魚<rt>ウインクブルー</rt></Ruby>",
		romaji: "samisiisinkaigyo",
		eng: "uinkuburu-",
		validInputs: [
			"samisiisinkaigyo",
			"samisiisincaigyo",
			"samisiishinkaigyo",
			"samisiishincaigyo",
			"samisiicinkaigyo",
			"samisiicincaigyo",
			"samishiisinkaigyo",
			"samishiisincaigyo",
			"samishiishinkaigyo",
			"samishiishincaigyo",
			"samishiicinkaigyo",
			"samishiicincaigyo",
			"samiciisinkaigyo",
			"samiciisincaigyo",
			"samiciishinkaigyo",
			"samiciishincaigyo",
			"samiciicinkaigyo",
			"samiciicincaigyo",
			"samisiisinnkaigyo",
			"samisiisinncaigyo",
			"samisiishinnkaigyo",
			"samisiishinncaigyo",
			"samisiicinnkaigyo",
			"samisiicinncaigyo",
			"samishiisinnkaigyo",
			"samishiisinncaigyo",
			"samishiishinnkaigyo",
			"samishiishinncaigyo",
			"samishiicinnkaigyo",
			"samishiicinncaigyo",
			"samiciisinnkaigyo",
			"samiciisinncaigyo",
			"samiciishinnkaigyo",
			"samiciishinncaigyo",
			"samiciicinnkaigyo",
			"samiciicinncaigyo"
		],
		validInputs2: ["uinkuburu-", "uincuburu-", "uinquburu-", "uinnkuburu-", "uinncuburu-", "uinnquburu-"]
	},
	{
		kanji: "<Ruby>暗黒の鬼婦神<rt>ブラックウィドウ</rt></Ruby>",
		romaji: "ankokunokihujin",
		eng: "burakkuwidou",
		validInputs: [
			"ankokunokihujin",
			"ankokunokihuzin",
			"ankokunokifujin",
			"ankokunokifuzin",
			"ankocunokihujin",
			"ankocunokihuzin",
			"ankocunokifujin",
			"ankocunokifuzin",
			"ankoqunokihujin",
			"ankoqunokihuzin",
			"ankoqunokifujin",
			"ankoqunokifuzin",
			"ancokunokihujin",
			"ancokunokihuzin",
			"ancokunokifujin",
			"ancokunokifuzin",
			"ancocunokihujin",
			"ancocunokihuzin",
			"ancocunokifujin",
			"ancocunokifuzin",
			"ancoqunokihujin",
			"ancoqunokihuzin",
			"ancoqunokifujin",
			"ancoqunokifuzin",
			"annkokunokihujin",
			"annkokunokihuzin",
			"annkokunokifujin",
			"annkokunokifuzin",
			"annkocunokihujin",
			"annkocunokihuzin",
			"annkocunokifujin",
			"annkocunokifuzin",
			"annkoqunokihujin",
			"annkoqunokihuzin",
			"annkoqunokifujin",
			"annkoqunokifuzin",
			"anncokunokihujin",
			"anncokunokihuzin",
			"anncokunokifujin",
			"anncokunokifuzin",
			"anncocunokihujin",
			"anncocunokihuzin",
			"anncocunokifujin",
			"anncocunokifuzin",
			"anncoqunokihujin",
			"anncoqunokihuzin",
			"anncoqunokifujin",
			"anncoqunokifuzin"
		],
		validInputs2: ["burakkuwidou", "buraccuwidou", "buraqquwidou"]
	},
	{
		kanji: "<Ruby>愛の放射線<rt>ラブシャワー</rt></Ruby>",
		romaji: "ainohousyasen",
		eng: "rabusyawa-",
		validInputs: ["ainohousyasen", "ainohoushasen"],
		validInputs2: ["rabusyawa-", "rabushawa-"]
	},
	{
		kanji: "<Ruby>記憶弾<rt>メモリーボム</rt></Ruby>",
		romaji: "kiokudan",
		eng: "memori-bomu",
		validInputs: ["kiokudan", "kiocudan", "kioqudan"],
		validInputs2: ["memori-bomu"]
	},
	{
		kanji: "<Ruby>流離の大俳人<rt>グレイトハイカー</rt></Ruby>",
		romaji: "sasurainodaihaijin",
		eng: "gureitohaika-",
		validInputs: ["sasurainodaihaijin", "sasurainodaihaizin"],
		validInputs2: ["gureitohaika-", "gureitohaica-"]
	},
	{
		kanji: "<Ruby>凶器の錯乱<rt>いまやりにいきます</rt></Ruby>",
		romaji: "kyoukinosakuran",
		eng: "imayariniikimasu",
		validInputs: ["kyoukinosakuran", "kyoukinosacuran", "kyoukinosaquran"],
		validInputs2: ["imayariniikimasu"]
	},
	{
		kanji: "<Ruby>幽体離脱<rt>ザ タッチ</rt></Ruby>",
		romaji: "yuutairidatu",
		eng: "zatatti",
		validInputs: ["yuutairidatu", "yuutairidatsu"],
		validInputs2: ["zatatti", "zatacchi"]
	},
	{
		kanji: "<Ruby>桃色吐息<rt>ピアノマッサージ</rt></Ruby>",
		romaji: "momoirotoiki",
		eng: "pianomassa-ji",
		validInputs: ["momoirotoiki"],
		validInputs2: ["pianomassa-ji", "pianomassa-zi"]
	},
	{
		kanji: "<Ruby>魔法美容師<rt>マジカルエステ</rt></Ruby>",
		romaji: "mahoubiyousi",
		eng: "majikaruesute",
		validInputs: ["mahoubiyousi", "mahoubiyoushi", "mahoubiyouci"],
		validInputs2: ["majikaruesute", "majicaruesute", "mazikaruesute", "mazicaruesute"]
	},
	{
		kanji: "<Ruby>薄っぺらな嘘<rt>ドッキリテクスチャー</rt></Ruby>",
		romaji: "usupperanauso",
		eng: "dokkiritekusutya-",
		validInputs: ["usupperanauso"],
		validInputs2: [
			"dokkiritekusutya-",
			"dokkiritekusucya-",
			"dokkiritekusucha-",
			"dokkiritecusutya-",
			"dokkiritecusucya-",
			"dokkiritecusucha-",
			"dokkiritequsutya-",
			"dokkiritequsucya-",
			"dokkiritequsucha-"
		]
	},
	{
		kanji: "<Ruby>伸縮自在の愛<rt>バンジーガム</rt></Ruby>",
		romaji: "sinsyukujizainoai",
		eng: "banji-gamu",
		validInputs: [
			"sinsyukujizainoai",
			"sinsyukuzizainoai",
			"sinsyucujizainoai",
			"sinsyucuzizainoai",
			"sinsyuqujizainoai",
			"sinsyuquzizainoai",
			"sinshukujizainoai",
			"sinshukuzizainoai",
			"sinshucujizainoai",
			"sinshucuzizainoai",
			"sinshuqujizainoai",
			"sinshuquzizainoai",
			"shinsyukujizainoai",
			"shinsyukuzizainoai",
			"shinsyucujizainoai",
			"shinsyucuzizainoai",
			"shinsyuqujizainoai",
			"shinsyuquzizainoai",
			"shinshukujizainoai",
			"shinshukuzizainoai",
			"shinshucujizainoai",
			"shinshucuzizainoai",
			"shinshuqujizainoai",
			"shinshuquzizainoai",
			"cinsyukujizainoai",
			"cinsyukuzizainoai",
			"cinsyucujizainoai",
			"cinsyucuzizainoai",
			"cinsyuqujizainoai",
			"cinsyuquzizainoai",
			"cinshukujizainoai",
			"cinshukuzizainoai",
			"cinshucujizainoai",
			"cinshucuzizainoai",
			"cinshuqujizainoai",
			"cinshuquzizainoai",
			"sinnsyukujizainoai",
			"sinnsyukuzizainoai",
			"sinnsyucujizainoai",
			"sinnsyucuzizainoai",
			"sinnsyuqujizainoai",
			"sinnsyuquzizainoai",
			"sinnshukujizainoai",
			"sinnshukuzizainoai",
			"sinnshucujizainoai",
			"sinnshucuzizainoai",
			"sinnshuqujizainoai",
			"sinnshuquzizainoai",
			"shinnsyukujizainoai",
			"shinnsyukuzizainoai",
			"shinnsyucujizainoai",
			"shinnsyucuzizainoai",
			"shinnsyuqujizainoai",
			"shinnsyuquzizainoai",
			"shinnshukujizainoai",
			"shinnshukuzizainoai",
			"shinnshucujizainoai",
			"shinnshucuzizainoai",
			"shinnshuqujizainoai",
			"shinnshuquzizainoai",
			"cinnsyukujizainoai",
			"cinnsyukuzizainoai",
			"cinnsyucujizainoai",
			"cinnsyucuzizainoai",
			"cinnsyuqujizainoai",
			"cinnsyuquzizainoai",
			"cinnshukujizainoai",
			"cinnshukuzizainoai",
			"cinnshucujizainoai",
			"cinnshucuzizainoai",
			"cinnshuqujizainoai",
			"cinnshuquzizainoai"
		],
		validInputs2: ["banji-gamu", "banzi-gamu", "bannji-gamu", "bannzi-gamu"]
	},
	{
		kanji: "<Ruby>切り裂き美容師<rt>シザーハンズ</rt></Ruby>",
		romaji: "kirisakibiyousi",
		eng: "siza-hanzu",
		validInputs: ["kirisakibiyousi", "kirisakibiyoushi", "kirisakibiyouci"],
		validInputs2: ["siza-hanzu", "shiza-hanzu", "ciza-hanzu", "siza-hannzu", "shiza-hannzu", "ciza-hannzu"]
	},
	{
		kanji: "<Ruby>てのひらを太陽に<rt>バイオハザード</rt></Ruby>",
		romaji: "tenohirawotaiyouni",
		eng: "baiohaza-do",
		validInputs: ["tenohirawotaiyouni"],
		validInputs2: ["baiohaza-do"]
	},
	{
		kanji: "<Ruby>廻天<rt>リッパーサイクロトロン</rt></Ruby>",
		romaji: "kaiten",
		eng: "rippa-saikurotoron",
		validInputs: ["kaiten", "caiten"],
		validInputs2: ["rippa-saikurotoron", "rippa-saicurotoron", "rippa-saiqurotoron"]
	},
	{
		kanji: "<Ruby>秘密の扉<rt>マジカルワーム</rt></Ruby>",
		romaji: "himitunotobira",
		eng: "majikaruwa-mu",
		validInputs: ["himitunotobira", "himitsunotobira"],
		validInputs2: ["majikaruwa-mu", "majicaruwa-mu", "mazikaruwa-mu", "mazicaruwa-mu"]
	},
	{
		kanji: "<Ruby>許されざる者<rt>ペインパッカー</rt></Ruby>",
		romaji: "yurusarezarumono",
		eng: "peinpakka-",
		validInputs: ["yurusarezarumono"],
		validInputs2: ["peinpakka-", "peinpacca-", "peinnpakka-", "peinnpacca-"]
	},
	{
		kanji: "<Ruby>太陽に灼かれて<rt>ライジングサン</rt></Ruby>",
		romaji: "taiyouniyakarete",
		eng: "raijingusan",
		validInputs: ["taiyouniyakarete", "taiyouniyacarete"],
		validInputs2: ["raijingusan", "raizingusan", "raijinngusan", "raizinngusan"]
	},
	{
		kanji: "<Ruby>不思議で便利な大風呂敷<rt>ファンファンクロス</rt></Ruby>",
		romaji: "husigidebenrinaooburosiki",
		eng: "fanfankurosu",
		validInputs: [
			"husigidebenrinaooburosiki",
			"husigidebenrinaooburoshiki",
			"husigidebenrinaooburociki",
			"hushigidebenrinaooburosiki",
			"hushigidebenrinaooburoshiki",
			"hushigidebenrinaooburociki",
			"hucigidebenrinaooburosiki",
			"hucigidebenrinaooburoshiki",
			"hucigidebenrinaooburociki",
			"fusigidebenrinaooburosiki",
			"fusigidebenrinaooburoshiki",
			"fusigidebenrinaooburociki",
			"fushigidebenrinaooburosiki",
			"fushigidebenrinaooburoshiki",
			"fushigidebenrinaooburociki",
			"fucigidebenrinaooburosiki",
			"fucigidebenrinaooburoshiki",
			"fucigidebenrinaooburociki",
			"husigidebennrinaooburosiki",
			"husigidebennrinaooburoshiki",
			"husigidebennrinaooburociki",
			"hushigidebennrinaooburosiki",
			"hushigidebennrinaooburoshiki",
			"hushigidebennrinaooburociki",
			"hucigidebennrinaooburosiki",
			"hucigidebennrinaooburoshiki",
			"hucigidebennrinaooburociki",
			"fusigidebennrinaooburosiki",
			"fusigidebennrinaooburoshiki",
			"fusigidebennrinaooburociki",
			"fushigidebennrinaooburosiki",
			"fushigidebennrinaooburoshiki",
			"fushigidebennrinaooburociki",
			"fucigidebennrinaooburosiki",
			"fucigidebennrinaooburoshiki",
			"fucigidebennrinaooburociki"
		],
		validInputs2: [
			"fanfankurosu",
			"fanfancurosu",
			"fanfanqurosu",
			"fanfannkurosu",
			"fanfanncurosu",
			"fanfannqurosu",
			"fannfankurosu",
			"fannfancurosu",
			"fannfanqurosu",
			"fannfannkurosu",
			"fannfanncurosu",
			"fannfannqurosu"
		]
	},
	{
		kanji: "<Ruby>超複眼<rt>スーパーアイ</rt></Ruby>",
		romaji: "tyouhukugan",
		eng: "su-pa-ai",
		validInputs: [
			"tyouhukugan",
			"tyouhucugan",
			"tyouhuqugan",
			"tyoufukugan",
			"tyoufucugan",
			"tyoufuqugan",
			"cyouhukugan",
			"cyouhucugan",
			"cyouhuqugan",
			"cyoufukugan",
			"cyoufucugan",
			"cyoufuqugan",
			"chouhukugan",
			"chouhucugan",
			"chouhuqugan",
			"choufukugan",
			"choufucugan",
			"choufuqugan"
		],
		validInputs2: ["su-pa-ai"]
	},
	{
		kanji: "<Ruby>俺の両手は機関銃<rt>ダブルマシンガン</rt></Ruby>",
		romaji: "orenoryoutehakikanjuu",
		eng: "daburumasingan",
		validInputs: [
			"orenoryoutehakikanjuu",
			"orenoryoutehakikanjyuu",
			"orenoryoutehakikanzyuu",
			"orenoryoutehakicanjuu",
			"orenoryoutehakicanjyuu",
			"orenoryoutehakicanzyuu",
			"orenoryoutehakikannjuu",
			"orenoryoutehakikannjyuu",
			"orenoryoutehakikannzyuu",
			"orenoryoutehakicannjuu",
			"orenoryoutehakicannjyuu",
			"orenoryoutehakicannzyuu"
		],
		validInputs2: [
			"daburumasingan",
			"daburumashingan",
			"daburumacingan",
			"daburumasinngan",
			"daburumashinngan",
			"daburumacinngan"
		]
	},
	{
		kanji: "<Ruby>裏窓の鳥<rt>シークレットウインドウ</rt></Ruby>",
		romaji: "uramadonotori",
		eng: "si-kurettouindou",
		validInputs: ["uramadonotori"],
		validInputs2: [
			"si-kurettouindou",
			"si-curettouindou",
			"si-qurettouindou",
			"shi-kurettouindou",
			"shi-curettouindou",
			"shi-qurettouindou",
			"ci-kurettouindou",
			"ci-curettouindou",
			"ci-qurettouindou",
			"si-kurettouinndou",
			"si-curettouinndou",
			"si-qurettouinndou",
			"shi-kurettouinndou",
			"shi-curettouinndou",
			"shi-qurettouinndou",
			"ci-kurettouindnou",
			"ci-curettouindnou",
			"ci-qurettouindnou"
		]
	},
	{
		kanji: "<Ruby>星を継ぐもの<rt>ベンジャミンバトン</rt></Ruby>",
		romaji: "hosiwotugumono",
		eng: "benjaminbaton",
		validInputs: [
			"hosiwotugumono",
			"hosiwotsugumono",
			"hoshiwotugumono",
			"hoshiwotsugumono",
			"hociwotugumono",
			"hociwotsugumono"
		],
		validInputs2: [
			"benjaminbaton",
			"benjyaminbaton",
			"benzyaminbaton",
			"benjaminnbaton",
			"benjyaminnbaton",
			"benzyaminnbaton",
			"bennjaminbaton",
			"bennjyaminbaton",
			"bennzyaminbaton",
			"bennjaminnbaton",
			"bennjyaminnbaton",
			"bennzyaminnbaton"
		]
	},
	{
		kanji: "<Ruby>七色弓箭<rt>レインボウ</rt></Ruby>",
		romaji: "nanairokyuusen",
		eng: "reinbou",
		validInputs: ["nanairokyuusen"],
		validInputs2: ["reinbou", "reinnbou"]
	},
	{
		kanji: "<Ruby>戦闘演武曲<rt>バトレカンタービレ</rt></Ruby>",
		romaji: "sentouenbukyoku",
		eng: "batorekanta-bire",
		validInputs: [
			"sentouenbukyoku",
			"sentouenbukyocu",
			"sentouenbukyoqu",
			"sentouennbukyoku",
			"sentouennbukyocu",
			"sentouennbukyoqu",
			"senntouenbukyoku",
			"senntouenbukyocu",
			"senntouenbukyoqu",
			"senntouennbukyoku",
			"senntouennbukyocu",
			"senntouennbukyoqu"
		],
		validInputs2: ["batorekanta-bire", "batorecanta-bire"]
	},
	{
		kanji: "<Ruby>念糸縫合<rt>ねんしほうごう</rt></Ruby>",
		romaji: "nensihougou",
		eng: "nensihougou",
		validInputs: ["nensihougou", "nenshihougou", "nencihougou", "nennsihougou", "nennshihougou", "nenncihougou"],
		validInputs2: ["nensihougou", "nenshihougou", "nencihougou", "nennsihougou", "nennshihougou", "nenncihougou"]
	},
	{
		kanji: "<Ruby>Zombie Girl<rt>ラヴィアンローズ</rt></Ruby>",
		romaji: "zonbiga-ru",
		eng: "ravianro-zu",
		validInputs: ["zonbiga-ru", "zonnbiga-ru"],
		validInputs2: ["ravianro-zu", "raviannro-zu"]
	},
	{
		kanji: "<Ruby>密室裁判<rt>クロスゲーム</rt></Ruby>",
		romaji: "missitusaiban",
		eng: "kurosuge-mu",
		validInputs: [
			"missitusaiban",
			"missitsusaiban",
			"misshitusaiban",
			"misshitsusaiban",
			"micchitusaiban",
			"micchitsusaiban"
		],
		validInputs2: ["kurosuge-mu", "curosuge-mu", "qurosuge-mu"]
	},
	{
		kanji: "<Ruby>神の共犯者<rt>かみのきょうはんしゃ</rt></Ruby>",
		romaji: "kaminokyouhansya",
		eng: "kaminokyouhansya",
		validInputs: ["kaminokyouhansya", "kaminokyouhansha", "caminokyouhansya", "caminokyouhansha"],
		validInputs2: ["kaminokyouhansya", "kaminokyouhansha", "caminokyouhansya", "caminokyouhansha"]
	},
	{
		kanji: "<Ruby>神の不在証明<rt>パーフェクトプラン</rt></Ruby>",
		romaji: "kaminohuzaisyoumei",
		eng: "pa-fekutopuran",
		validInputs: [
			"kaminohuzaisyoumei",
			"kaminohuzaishoumei",
			"kaminofuzaisyoumei",
			"kaminofuzaishoumei",
			"caminohuzaisyoumei",
			"caminohuzaishoumei",
			"caminofuzaisyoumei",
			"caminofuzaishoumei"
		],
		validInputs2: ["pa-fekutopuran", "pa-fecutopuran", "pa-fequtopuran"]
	},
	{
		kanji: "<Ruby>監獄ロック<rt>スモーキージェイル</rt></Ruby>",
		romaji: "kangokurokku",
		eng: "sumo-ki-jeiru",
		validInputs: [
			"kangokurokku",
			"kangokuroccu",
			"kangokuroqqu",
			"kangocurokku",
			"kangocuroccu",
			"kangocuroqqu",
			"kangoqurokku",
			"kangoquroccu",
			"kangoquroqqu",
			"cangokurokku",
			"cangokuroccu",
			"cangokuroqqu",
			"cangocurokku",
			"cangocuroccu",
			"cangocuroqqu",
			"cangoqurokku",
			"cangoquroccu",
			"cangoquroqqu",
			"kanngokurokku",
			"kanngokuroccu",
			"kanngokuroqqu",
			"kanngocurokku",
			"kanngocuroccu",
			"kanngocuroqqu",
			"kanngoqurokku",
			"kanngoquroccu",
			"kanngoquroqqu",
			"canngokurokku",
			"canngokuroccu",
			"canngokuroqqu",
			"canngocurokku",
			"canngocuroccu",
			"canngocuroqqu",
			"canngoqurokku",
			"canngoquroccu",
			"canngoquroqqu"
		],
		validInputs2: ["sumo-ki-jeiru", "sumo-ki-jyeiru", "sumo-ki-zyeiru"]
	},
	{
		kanji: "<Ruby>紫煙機兵隊<rt>ディープパープル</rt></Ruby>",
		romaji: "sienkiheitai",
		eng: "dhi-pupa-puru",
		validInputs: ["sienkiheitai", "shienkiheitai", "cienkiheitai", "siennkiheitai", "shiennkiheitai", "ciennkiheitai"],
		validInputs2: ["dhi-pupa-puru", "delii-pupa-puru", "dexi-pupa-puru"]
	},
	{
		kanji: "<Ruby>恋のエチュード<rt>さいきんおせん</rt></Ruby>",
		romaji: "koinoetyu-do",
		eng: "saikinnosen",
		validInputs: ["koinoetyu-do", "koinoecyu-do", "koinoechu-do", "coinoetyu-do", "coinoecyu-do", "coinoechu-do"],
		validInputs2: ["saikinnosen"]
	},
	{
		kanji: "<Ruby>墨攻<rt>lsdf</rt></Ruby>",
		romaji: "bokukou",
		eng: "lsdf",
		validInputs: ["bokukou", "bokucou", "bocukou", "bocucou", "boqukou", "boqucou"],
		validInputs2: ["lsdf"]
	},
	{
		kanji: "<Ruby>爆発的推進力<rt>オーラバースト</rt></Ruby>",
		romaji: "bakuhatutekisuisinryoku",
		eng: "o-raba-suto",
		validInputs: [
			"bakuhatutekisuisinryoku",
			"bakuhatutekisuisinryocu",
			"bakuhatutekisuisinryoqu",
			"bakuhatutekisuishinryoku",
			"bakuhatutekisuishinryocu",
			"bakuhatutekisuishinryoqu",
			"bakuhatutekisuicinryoku",
			"bakuhatutekisuicinryocu",
			"bakuhatutekisuicinryoqu",
			"bakuhatsutekisuisinryoku",
			"bakuhatsutekisuisinryocu",
			"bakuhatsutekisuisinryoqu",
			"bakuhatsutekisuishinryoku",
			"bakuhatsutekisuishinryocu",
			"bakuhatsutekisuishinryoqu",
			"bakuhatsutekisuicinryoku",
			"bakuhatsutekisuicinryocu",
			"bakuhatsutekisuicinryoqu",
			"bacuhatutekisuisinryoku",
			"bacuhatutekisuisinryocu",
			"bacuhatutekisuisinryoqu",
			"bacuhatutekisuishinryoku",
			"bacuhatutekisuishinryocu",
			"bacuhatutekisuishinryoqu",
			"bacuhatutekisuicinryoku",
			"bacuhatutekisuicinryocu",
			"bacuhatutekisuicinryoqu",
			"bacuhatsutekisuisinryoku",
			"bacuhatsutekisuisinryocu",
			"bacuhatsutekisuisinryoqu",
			"bacuhatsutekisuishinryoku",
			"bacuhatsutekisuishinryocu",
			"bacuhatsutekisuishinryoqu",
			"bacuhatsutekisuicinryoku",
			"bacuhatsutekisuicinryocu",
			"bacuhatsutekisuicinryoqu",
			"baquhatutekisuisinryoku",
			"baquhatutekisuisinryocu",
			"baquhatutekisuisinryoqu",
			"baquhatutekisuishinryoku",
			"baquhatutekisuishinryocu",
			"baquhatutekisuishinryoqu",
			"baquhatutekisuicinryoku",
			"baquhatutekisuicinryocu",
			"baquhatutekisuicinryoqu",
			"baquhatsutekisuisinryoku",
			"baquhatsutekisuisinryocu",
			"baquhatsutekisuisinryoqu",
			"baquhatsutekisuishinryoku",
			"baquhatsutekisuishinryocu",
			"baquhatsutekisuishinryoqu",
			"baquhatsutekisuicinryoku",
			"baquhatsutekisuicinryocu",
			"baquhatsutekisuicinryoqu",
			"bakuhatutekisuisinnryoku",
			"bakuhatutekisuisinnryocu",
			"bakuhatutekisuisinnryoqu",
			"bakuhatutekisuishinnryoku",
			"bakuhatutekisuishinnryocu",
			"bakuhatutekisuishinnryoqu",
			"bakuhatutekisuicinnryoku",
			"bakuhatutekisuicinnryocu",
			"bakuhatutekisuicinnryoqu",
			"bakuhatsutekisuisinnryoku",
			"bakuhatsutekisuisinnryocu",
			"bakuhatsutekisuisinnryoqu",
			"bakuhatsutekisuishinnryoku",
			"bakuhatsutekisuishinnryocu",
			"bakuhatsutekisuishinnryoqu",
			"bakuhatsutekisuicinnryoku",
			"bakuhatsutekisuicinnryocu",
			"bakuhatsutekisuicinnryoqu",
			"bacuhatutekisuisinnryoku",
			"bacuhatutekisuisinnryocu",
			"bacuhatutekisuisinnryoqu",
			"bacuhatutekisuishinnryoku",
			"bacuhatutekisuishinnryocu",
			"bacuhatutekisuishinnryoqu",
			"bacuhatutekisuicinnryoku",
			"bacuhatutekisuicinnryocu",
			"bacuhatutekisuicinnryoqu",
			"bacuhatsutekisuisinnryoku",
			"bacuhatsutekisuisinnryocu",
			"bacuhatsutekisuisinnryoqu",
			"bacuhatsutekisuishinnryoku",
			"bacuhatsutekisuishinnryocu",
			"bacuhatsutekisuishinnryoqu",
			"bacuhatsutekisuicinnryoku",
			"bacuhatsutekisuicinnryocu",
			"bacuhatsutekisuicinnryoqu",
			"baquhatutekisuisinnryoku",
			"baquhatutekisuisinnryocu",
			"baquhatutekisuisinnryoqu",
			"baquhatutekisuishinnryoku",
			"baquhatutekisuishinnryocu",
			"baquhatutekisuishinnryoqu",
			"baquhatutekisuicinnryoku",
			"baquhatutekisuicinnryocu",
			"baquhatutekisuicinnryoqu",
			"baquhatsutekisuisinnryoku",
			"baquhatsutekisuisinnryocu",
			"baquhatsutekisuisinnryoqu",
			"baquhatsutekisuishinnryoku",
			"baquhatsutekisuishinnryocu",
			"baquhatsutekisuishinnryoqu",
			"baquhatsutekisuicinnryoku",
			"baquhatsutekisuicinnryocu",
			"baquhatsutekisuicinnryoqu"
		],
		validInputs2: ["o-raba-suto"]
	},
	{
		kanji: "<Ruby>双頭の蛇の正体<rt>サンダースネーク</rt></Ruby>",
		romaji: "soutounohebinosyoutai",
		eng: "sanda-sune-ku",
		validInputs: ["soutounohebinosyoutai", "soutounohebinoshoutai"],
		validInputs2: [
			"sanda-sune-ku",
			"sanda-sune-cu",
			"sanda-sune-qu",
			"sannda-sune-ku",
			"sannda-sune-cu",
			"sannda-sune-qu"
		]
	},
	{
		kanji: "<Ruby>双頭の蛇による二重唱<rt>ソングオブディフェンス</rt></Ruby>",
		romaji: "soutounohebiniyorunijuusyou",
		eng: "songuobudhifensu",
		validInputs: [
			"soutounohebiniyorunijuusyou",
			"soutounohebiniyorunijuushou",
			"soutounohebiniyorunijyuusyou",
			"soutounohebiniyorunijyuushou",
			"soutounohebiniyorunizyuusyou",
			"soutounohebiniyorunizyuushou"
		],
		validInputs2: [
			"songuobudhifensu",
			"sonnguobudhifensu",
			"songuobudelifensu",
			"sonnguobudelifensu",
			"songuobudexifensu",
			"sonnguobudexifensu"
		]
	},
	{
		kanji: "<Ruby>体は全部知っている<rt>ボディアンドソウル</rt></Ruby>",
		romaji: "karadahazenbusitteiru",
		eng: "bodhiandosouru",
		validInputs: [
			"karadahazenbusitteiru",
			"karadahazenbushitteiru",
			"karadahazenbucitteiru",
			"caradahazenbusitteiru",
			"caradahazenbushitteiru",
			"caradahazenbucitteiru",
			"karadahazennbusitteiru",
			"karadahazennbushitteiru",
			"karadahazennbucitteiru",
			"caradahazennbusitteiru",
			"caradahazennbushitteiru",
			"caradahazennbucitteiru"
		],
		validInputs2: [
			"bodhiandosouru",
			"bodeliiandosouru",
			"bodexiandosouru",
			"bodhianndosouru",
			"bodeliianndosouru",
			"bodexianndosouru"
		]
	},
	{
		kanji: "<Ruby>14人の悪魔<rt>14にんのあくま</rt></Ruby>",
		romaji: "14ninnnoakuma",
		eng: "14ninnnoakuma",
		validInputs: ["14ninnnoakuma", "14ninnnoacuma", "14ninnnoaquma"],
		validInputs2: ["14ninnnoakuma", "14ninnnoacuma", "14ninnnoaquma"]
	},
	{
		kanji: "<Ruby>TUBE<rt>イナムラ</rt></Ruby>",
		romaji: "tyu-bu",
		eng: "inamura",
		validInputs: ["tyu-bu", "cyu-bu", "chu-bu"],
		validInputs2: ["inamura"]
	},
	{
		kanji: "<Ruby>渦波<rt>トルネイブ</rt></Ruby>",
		romaji: "uzunami",
		eng: "toruneibu",
		validInputs: ["uzunami"],
		validInputs2: ["toruneibu"]
	},
	{
		kanji: "<Ruby>大波<rt>ビックウォール</rt></Ruby>",
		romaji: "oonami",
		eng: "bikkuwho-ru",
		validInputs: ["oonami"],
		validInputs2: ["bikkuwho-ru", "biccuwho-ru", "biqquwho-ru"]
	},
	{
		kanji: "<Ruby>謝債発行機<rt>レンタルポッド</rt></Ruby>",
		romaji: "syasaihakkouki",
		eng: "rentarupoddo",
		validInputs: ["syasaihakkouki", "syasaihaccouki", "shasaihakkouki", "shasaihaccouki"],
		validInputs2: ["rentarupoddo", "renntarupoddo"]
	},
	{
		kanji: "<Ruby>漆黒の処刑台<rt>オンバサラ</rt></Ruby>",
		romaji: "sikkokunosyokeidai",
		eng: "onbasara",
		validInputs: [
			"sikkokunosyokeidai",
			"sikkokunoshokeidai",
			"sikkocunosyokeidai",
			"sikkocunoshokeidai",
			"sikkoqunosyokeidai",
			"sikkoqunoshokeidai",
			"siccokunosyokeidai",
			"siccokunoshokeidai",
			"siccocunosyokeidai",
			"siccocunoshokeidai",
			"siccoqunosyokeidai",
			"siccoqunoshokeidai",
			"shikkokunosyokeidai",
			"shikkokunoshokeidai",
			"shikkocunosyokeidai",
			"shikkocunoshokeidai",
			"shikkoqunosyokeidai",
			"shikkoqunoshokeidai",
			"shiccokunosyokeidai",
			"shiccokunoshokeidai",
			"shiccocunosyokeidai",
			"shiccocunoshokeidai",
			"shiccoqunosyokeidai",
			"shiccoqunoshokeidai",
			"cikkokunosyokeidai",
			"cikkokunoshokeidai",
			"cikkocunosyokeidai",
			"cikkocunoshokeidai",
			"cikkoqunosyokeidai",
			"cikkoqunoshokeidai",
			"ciccokunosyokeidai",
			"ciccokunoshokeidai",
			"ciccocunosyokeidai",
			"ciccocunoshokeidai",
			"ciccoqunosyokeidai",
			"ciccoqunoshokeidai"
		],
		validInputs2: ["onbasara", "onnbasara"]
	},
	{
		kanji: "<Ruby>卵男<rt>ミサイルマン</rt></Ruby>",
		romaji: "tamagootoko",
		eng: "misairuman",
		validInputs: ["tamagootoko", "tamagootoco"],
		validInputs2: ["misairuman"]
	},
	{
		kanji: "<Ruby>超破壊拳<rt>ビックバンインパクト</rt></Ruby>",
		romaji: "tyouhakaiken",
		eng: "bikkubanninpakuto",
		validInputs: ["tyouhakaiken", "tyouhacaiken", "cyouhakaiken", "cyouhacaiken", "chouhakaiken", "chouhacaiken"],
		validInputs2: [
			"bikkubanninpakuto",
			"bikkubanninpacuto",
			"bikkubanninpaquto",
			"biccubanninpakuto",
			"biccubanninpacuto",
			"biccubanninpaquto",
			"biqqubanninpakuto",
			"biqqubanninpacuto",
			"biqqubanninpaquto"
		]
	},
	{
		kanji: "<Ruby>裏窓<rt>リトルアイ</rt></Ruby>",
		romaji: "uramado",
		eng: "ritoruai",
		validInputs: ["uramado"],
		validInputs2: ["ritoruai"]
	},
	{
		kanji: "<Ruby>命の音<rt>カウントダウン</rt></Ruby>",
		romaji: "inotinooto",
		eng: "kauntodaun",
		validInputs: ["inotinooto", "inochinooto"],
		validInputs2: ["kauntodaun", "cauntodaun", "kaunntodaun", "caunntodaun"]
	},
	{
		kanji: "<Ruby>11人いる<rt>サイレントマジョリティー</rt></Ruby>",
		romaji: "11ninniru",
		eng: "sairentomajorithi-",
		validInputs: ["11ninniru"],
		validInputs2: [
			"sairentomajorithi-",
			"sairentomajoriteli-",
			"sairentomajoritexi-",
			"sairentomajyorithi-",
			"sairentomajyoriteli-",
			"sairentomajyoritexi-",
			"sairentomazyorithi-",
			"sairentomazyoriteli-",
			"sairentomazyoritexi-",
			"sairentomazyorithi-",
			"sairentomazyoriteli-",
			"sairentomazyoritexi-",
			"sairenntomajorithi-",
			"sairenntomajoriteli-",
			"sairenntomajoritexi-",
			"sairenntomajyorithi-",
			"sairenntomajyoriteli-",
			"sairenntomajyoritexi-",
			"sairenntomazyorithi-",
			"sairenntomazyoriteli-",
			"sairenntomazyoritexi-",
			"sairenntomazyorithi-",
			"sairenntomazyoriteli-",
			"sairenntomazyoritexi-"
		]
	},
	{
		kanji: "<Ruby>damage<rt>ダメージ</rt></Ruby>",
		romaji: "dame-ji",
		eng: "dame-ji",
		validInputs: ["dame-ji", "dame-zi"],
		validInputs2: ["dame-ji", "dame-zi"]
	}
];
