//小説の言葉
export const novelWords = [
	{ kanji: "魔法", romaji: "mahou", eng: "magic" },
	{ kanji: "魔法使い", romaji: "mahoutukai", eng: "wizard" },
	{ kanji: "魔法陣", romaji: "mahoujinn", eng: "magic circle" },
	{ kanji: "呪文", romaji: "jyumonn", eng: "spell" },
	{ kanji: "杖", romaji: "tue", eng: "wand" },
	{ kanji: "剣", romaji: "kenn", eng: "sword" },
	{ kanji: "竜", romaji: "ryuu", eng: "dragon" },
	{ kanji: "魔王", romaji: "maou", eng: "demon king" },
	{ kanji: "冒険", romaji: "boukenn", eng: "adventure" },
	{ kanji: "騎士", romaji: "kisi", eng: "knight" },
	{ kanji: "冒険者", romaji: "boukennsya", eng: "adventurer" },
	{ kanji: "勇者", romaji: "yuusya", eng: "hero" },
	{ kanji: "魔獣", romaji: "majyuu", eng: "magical beast" },
	{ kanji: "召喚", romaji: "syoukann", eng: "summon" },
	{ kanji: "魔法剣", romaji: "mahoukenn", eng: "magic sword" },
	{ kanji: "魔力", romaji: "maryoku", eng: "magical power" },
	{ kanji: "ドラゴン", romaji: "doragonn", eng: "dragon" },
	{ kanji: "予言書", romaji: "yogennsyo", eng: "prophecy book" },
	{ kanji: "魔術", romaji: "majyutu", eng: "magic art" },
	{ kanji: "妖精", romaji: "yousei", eng: "fairy" },
	{ kanji: "幻獣", romaji: "gennjyuu", eng: "phantom beast" },
	{ kanji: "神話", romaji: "sinnwa", eng: "myth" },
	{ kanji: "魔法戦士", romaji: "mahousennsi", eng: "magic warrior" },
	{ kanji: "黒魔術", romaji: "kuromajyutu", eng: "black magic" },
	{ kanji: "聖剣", romaji: "seikenn", eng: "holy sword" },
	{ kanji: "魔界", romaji: "makai", eng: "demon world" },
	{ kanji: "魔法書", romaji: "mahousyo", eng: "magic book" },
	{ kanji: "魔女", romaji: "majyo", eng: "witch" },
	{ kanji: "魔法学校", romaji: "mahougakkou", eng: "magic school" },
	{ kanji: "宇宙船", romaji: "utyuusenn", eng: "spaceship" },
	{ kanji: "未来", romaji: "mirai", eng: "future" },
	{ kanji: "ロボット", romaji: "robotto", eng: "robot" },
	{ kanji: "クローン", romaji: "kuro-nn", eng: "clone" },
	{ kanji: "超能力", romaji: "tyounouryoku", eng: "psychic powers" },
	{ kanji: "タイムトラベル", romaji: "taimutoraberu", eng: "time travel" },
	{ kanji: "異星人", romaji: "iseijinn", eng: "extraterrestrial" },
	{ kanji: "宇宙", romaji: "utyuu", eng: "space" },
	{ kanji: "宇宙戦争", romaji: "utyuusensou", eng: "space war" },
	{ kanji: "サイバーパンク", romaji: "saiba-pannku", eng: "cyberpunk" },
	{ kanji: "パラレルワールド", romaji: "parareruwa-rudo", eng: "parallel world" },
	{ kanji: "人工知能", romaji: "jinnkoutinou", eng: "artificial intelligence" },
	{ kanji: "アンドロイド", romaji: "anndoroido", eng: "android" },
	{ kanji: "サイボーグ", romaji: "saibo-gu", eng: "cyborg" },
	{ kanji: "宇宙人", romaji: "utyuujinn", eng: "alien" },
	{ kanji: "ディストピア", romaji: "dhisutopia", eng: "dystopia" },
	{ kanji: "宇宙開発", romaji: "utyuukaihatu", eng: "space development" },
	{ kanji: "宇宙ステーション", romaji: "utyuusute-syonn", eng: "space station" },
	{ kanji: "宇宙探査", romaji: "utyuutannsa", eng: "space exploration" },
	{ kanji: "ロボット工学", romaji: "robottokougaku", eng: "robotics" },
	{ kanji: "宇宙旅行", romaji: "utyuuryokou", eng: "space travel" },
	{ kanji: "宇宙開拓", romaji: "utyuukaitaku", eng: "space colonization" },
	{ kanji: "宇宙時代", romaji: "utyuujidai", eng: "space age" },
	{ kanji: "宇宙エレベーター", romaji: "utyuuerebe-ta-", eng: "space elevator" },
	{ kanji: "宇宙戦艦", romaji: "utyuusennkann", eng: "space battleship" },
	{ kanji: "クローン技術", romaji: "kuro-nngijyutu", eng: "clone technology" },
	{ kanji: "テレポーテーション", romaji: "terepo-te-syonn", eng: "teleportation" },
	{ kanji: "宇宙移民", romaji: "utyuuiminn", eng: "space migration" },
	{ kanji: "人工衛星", romaji: "jinnkoueisei", eng: "artificial satellite" },
	{ kanji: "仮想現実", romaji: "kasougennjitu", eng: "virtual reality" },
	{ kanji: "サイバーネットワーク", romaji: "saiba-nettowa-ku", eng: "cyber network" },
	{ kanji: "グリッドコンピューティング", romaji: "guriddokonnpyu-thinngu", eng: "grid computing" },
	{ kanji: "バーチャルリアリティ", romaji: "ba-charuriarithi", eng: "virtual reality" },
	{ kanji: "アステロイド", romaji: "asuteroido", eng: "asteroid" },
	{ kanji: "惑星", romaji: "wakusei", eng: "planet" },
	{ kanji: "太陽系", romaji: "taiyoukei", eng: "solar system" },
	{ kanji: "恒星", romaji: "kousei", eng: "star" },
	{ kanji: "時空間", romaji: "jikuukann", eng: "spacetime" },
	{ kanji: "ブラックホール", romaji: "burakkuho-ru", eng: "black hole" },
	{ kanji: "宇宙論", romaji: "utyuuronn", eng: "cosmology" },
	{ kanji: "宇宙船乗組員", romaji: "utyuusennnorikumiinn", eng: "spaceship crew" },
	{ kanji: "宇宙エネルギー", romaji: "utyuuenerugi-", eng: "space energy" },
	{ kanji: "宇宙観測", romaji: "utyuukannsoku", eng: "space observation" },
	{ kanji: "宇宙ステーションクルー", romaji: "utyuusute-syonnkuru-", eng: "space station crew" },
	{ kanji: "宇宙線", romaji: "utyuusenn", eng: "cosmic rays" },
	{ kanji: "スペースコロニー", romaji: "supe-sukoroni-", eng: "space colony" },
	{ kanji: "テラフォーミング", romaji: "terafo-minngu", eng: "terraforming" },
	{ kanji: "サイボーグ技術", romaji: "saibo-gugijyutu", eng: "cyborg technology" },
	{
		kanji: "宇宙ステーションメンテナンス",
		romaji: "utyuusute-syonnmenntenannsu",
		eng: "space station maintenance"
	},
	{ kanji: "宇宙環境", romaji: "utyuukannkyou", eng: "space environment" },
	{ kanji: "惑星探査機", romaji: "wakuseitannsaki", eng: "planetary probe" },
	{ kanji: "宇宙探査機", romaji: "utyuutannsaki", eng: "space probe" },
	{ kanji: "地球外生命体", romaji: "tikyuugaiseimeitai", eng: "extraterrestrial life" },
	{ kanji: "サイバースペース", romaji: "saiba-supe-su", eng: "cyberspace" },
	{ kanji: "量子コンピューター", romaji: "ryousikonnpyu-ta-", eng: "quantum computer" },
	{ kanji: "テクノロジー", romaji: "tekunoroji-", eng: "technology" },
	{ kanji: "宇宙開発計画", romaji: "utyuukaihatukeikaku", eng: "space development plan" },
	{ kanji: "スペースシャトル", romaji: "supe-susyatoru", eng: "space shuttle" },
	{ kanji: "推理小説", romaji: "suirisyousetu", eng: "detective novel" },
	{ kanji: "事件", romaji: "jikenn", eng: "case" },
	{ kanji: "探偵", romaji: "tanntei", eng: "detective" },
	{ kanji: "ミステリー", romaji: "misuteri-", eng: "mystery" },
	{ kanji: "犯罪", romaji: "hannzai", eng: "crime" },
	{ kanji: "証拠", romaji: "syouko", eng: "evidence" },
	{ kanji: "アリバイ", romaji: "aribai", eng: "alibi" },
	{ kanji: "殺人", romaji: "satujinn", eng: "murder" },
	{ kanji: "謎", romaji: "nazo", eng: "puzzle" },
	{ kanji: "推理小説家", romaji: "suirisyousetuka", eng: "mystery writer" },
	{ kanji: "密室", romaji: "missitu", eng: "locked room" },
	{ kanji: "事件現場", romaji: "jikenngennba", eng: "crime scene" },
	{ kanji: "犯人", romaji: "hannninn", eng: "criminal" },
	{ kanji: "探偵助手", romaji: "tannteijyosyu", eng: "detective assistant" },
	{ kanji: "怪盗", romaji: "kaitou", eng: "phantom thief" },
	{ kanji: "暗号", romaji: "anngou", eng: "cipher" },
	{ kanji: "推理力", romaji: "suiriryoku", eng: "deductive reasoning" },
	{ kanji: "サスペンス", romaji: "sasupennsu", eng: "suspense" },
	{ kanji: "アクション", romaji: "akusyonn", eng: "action" },
	{ kanji: "探偵小説", romaji: "tannteisyousetu", eng: "detective novel" },
	{ kanji: "事件簿", romaji: "jikennbo", eng: "case file" },
	{ kanji: "密室殺人", romaji: "missitusatujinn", eng: "locked-room murder" },
	{ kanji: "探偵事務所", romaji: "tannteijimusyo", eng: "detective agency" },
	{ kanji: "証人", romaji: "syouninn", eng: "witness" },
	{ kanji: "事件解決", romaji: "jikennkaiketu", eng: "case resolution" },
	{ kanji: "黒幕", romaji: "kuromaku", eng: "mastermind" },
	{ kanji: "ノワール", romaji: "nowa-ru", eng: "noir" },
	{ kanji: "探偵小説の名探偵", romaji: "tannteisyousetunomeitanntei", eng: "famous detective in detective novels" },
	{ kanji: "犯罪捜査", romaji: "hannzaisousa", eng: "criminal investigation" },
	{ kanji: "証言", romaji: "syougenn", eng: "testimony" }
];

//ハンターハンター
export const hunterWords = [
	{ kanji: "百式観音", romaji: "hyakusikikannnonn", eng: "ひゃくしきかんのん" },
	{ kanji: "百式観音壱乃掌", romaji: "hyakusikikannnonnitinote", eng: "ひゃくしきかんのんいちのて" },
	{ kanji: "百式観音零の掌", romaji: "hyakusikikannnonnzeronote", eng: "ひゃくしきかんのんぜろのて" },
	{ kanji: "百式観音九十九の掌", romaji: "hyakusikikannnonntukumonote", eng: "ひゃくしきかんのんつくものて" },
	{ kanji: "蚤弾", romaji: "huri-damu", eng: "フリーダム" },
	{ kanji: "死体と遊ぶな子供達", romaji: "sitaitoasobunakodomotati", eng: "リビングデッドドールズ" },
	{ kanji: "180分の恋奴隷", romaji: "180hunnnokoidorei", eng: "インスタントラヴァー" },
	{ kanji: "俤人", romaji: "omokagebito", eng: "ソウルドール" },
	{ kanji: "魂呼ばい", romaji: "tamayobai", eng: "たまよばい" },
	{ kanji: "人形受胎", romaji: "ninngyoujyutai", eng: "ドールキャッチャー" },
	{ kanji: "死亡遊戯", romaji: "sibouyuugi", eng: "ダツDEダーツ" },
	{ kanji: "百万回生きた猫", romaji: "hyakumannkaiikitaneko", eng: "ネコノナマエ" },
	{ kanji: "気狂いピエロ", romaji: "kiguruipiero", eng: "クレイジースロット" },
	{ kanji: "死神の円舞曲", romaji: "sinigaminoennbukyoku", eng: "サイレントワルツ" },
	{ kanji: "踊る気儘な火人形", romaji: "odorukimamanahininngyou", eng: "ダンシングドール" },
	{ kanji: "虎咬真拳", romaji: "kokousinnkenn", eng: "ここうしんけん" },
	{ kanji: "二人セゾン", romaji: "hutarisezonn", eng: "キミガイナイ" },
	{ kanji: "蛇咬の舞", romaji: "dakounomai", eng: "だこうのまい" },
	{ kanji: "散弾独楽哀歌", romaji: "sanndanngomaaika", eng: "ショットガンブルース" },
	{ kanji: "戦闘舞踏曲", romaji: "senntoubutoukyoku", eng: "たたかいのワルツ" },
	{ kanji: "竜巻独楽", romaji: "tatumakigoma", eng: "たつまきごま" },
	{ kanji: "超不協輪怨", romaji: "tyouhukyouwaonn", eng: "シークレットノイズ" },
	{ kanji: "雷掌", romaji: "raisyou", eng: "イズツシ" },
	{ kanji: "神速", romaji: "sinnsoku", eng: "カンムル" },
	{ kanji: "落雷", romaji: "rakurai", eng: "ナルカミ" },
	{ kanji: "絶対時間", romaji: "zettaijikann", eng: "エンペラータイム" },
	{ kanji: "律する小指の鎖", romaji: "rissurukoyubinokusari", eng: "ジャッジメントチェーン" },
	{ kanji: "奪う人差し指の鎖", romaji: "ubauhitosasiyubinokusari", eng: "スチールチェーン" },
	{ kanji: "導く薬指の鎖", romaji: "mitibikukusuriyubinokusari", eng: "ダウジングチェーン" },
	{ kanji: "束縛する中指の鎖", romaji: "sokubakusurunakayubinokusari", eng: "チェーンジェイル" },
	{ kanji: "癒す親指の鎖", romaji: "iyasuoyayubinokusari", eng: "ホーリーチェーン" },
	{ kanji: "密室遊魚", romaji: "missituyuugyo", eng: "インドアフィッシュ" },
	{ kanji: "人間の証明", romaji: "ninngennnosyoumei", eng: "オーダースタンプ" },
	{ kanji: "転校生", romaji: "tennkousei", eng: "コンバートハンズ" },
	{ kanji: "番いの破壊者", romaji: "tugainohakaisya", eng: "サンアンドムーン" },
	{ kanji: "盗賊の極意", romaji: "touzokunogokui", eng: "スキルハンター" },
	{ kanji: "栞のテーマ", romaji: "siorinote-ma", eng: "ダブルフェイス" },
	{ kanji: "一握りの火薬", romaji: "hitonigirinokayaku", eng: "リトルフラワー" },
	{ kanji: "神の左手悪魔の右手", romaji: "kaminohidariteakumanomigite", eng: "ギャラリーフェイク" },
	{ kanji: "黒い賢人", romaji: "kuroikennjinn", eng: "ブラックゴレイヌ" },
	{ kanji: "白い賢人", romaji: "siroikennjinn", eng: "ホワイトゴレイヌ" },
	{ kanji: "ジャジャン拳", romaji: "jyajyannkenn", eng: "じゃじゃんけん" },
	{ kanji: "血いさな世界", romaji: "tiisanasekai", eng: "ブラッディメアリー" },
	{ kanji: "審美的転生注射", romaji: "sinnbitekitennseityuusya", eng: "クイーンショット" },
	{ kanji: "遊戯王", romaji: "yuugiou", eng: "カルドセプト" },
	{ kanji: "デメちゃん", romaji: "demetyann", eng: "でめちゃん" },
	{ kanji: "大和撫子七変化", romaji: "yamatonadesikositihennge", eng: "ライダーズハイ" },
	{ kanji: "麟粉乃愛泉", romaji: "rinnpunnnoaisenn", eng: "スピリチュアルメッセージ" },
	{ kanji: "蠅の王", romaji: "haenoou", eng: "ベルゼブブ" },
	{ kanji: "縁の下の十一人", romaji: "ennnositanojyuuitininn", eng: "イレブンブラックチルドレン" },
	{ kanji: "携帯する他人の運命", romaji: "keitaisurutaninnnounnmei", eng: "ブラックボイス" },
	{ kanji: "暗い宿", romaji: "kuraiyado", eng: "ホテル・ラフレシア" },
	{ kanji: "物真似鳥", romaji: "monomanedori", eng: "ジェイプシフター" },
	{ kanji: "機械に巣食う棘", romaji: "kikainisukuutoge", eng: "マシンイーター" },
	{ kanji: "龍星群", romaji: "ryuuseigunn", eng: "ドラゴンダイヴ" },
	{ kanji: "龍頭戯画", romaji: "ryuutougiga", eng: "ドラゴンヘッド" },
	{ kanji: "牙突", romaji: "gatotu", eng: "ドランゴンランス" },
	{ kanji: "蠅の仕事", romaji: "haenosigoto", eng: "サイレントワーカー" },
	{ kanji: "天上不知唯我独損", romaji: "tennjyouhutiyuigadokusonn", eng: "ハコワレ" },
	{ kanji: "天使の自動筆記", romaji: "tennsinojidouhikki", eng: "ラブリーゴーストライター" },
	{ kanji: "黒子無想", romaji: "kokusimusou", eng: "テレプシコーラ" },
	{ kanji: "玩具修理者", romaji: "ganngusyuurisya", eng: "ドクタープライス" },
	{ kanji: "窓を開く者", romaji: "madowohirakumono", eng: "スクリーム" },
	{ kanji: "四次元マンション", romaji: "yojigennmannsyonn", eng: "ハイドアンドシーク" },
	{ kanji: "淋しい深海魚", romaji: "samisiisinnkaigyo", eng: "ウインクブルー" },
	{ kanji: "暗黒の鬼婦神", romaji: "annkokunokihujinn", eng: "ブラックウィドウ" },
	{ kanji: "愛の放射線", romaji: "ainohousyasenn", eng: "ラブシャワー" },
	{ kanji: "記憶弾", romaji: "kiokudann", eng: "メモリーボム" },
	{ kanji: "流離の大俳人", romaji: "sasurainodaihaijinn", eng: "グレイトハイカー" },
	{ kanji: "凶器の錯乱", romaji: "kyoukinosakurann", eng: "いまやりにゆきます" },
	{ kanji: "幽体離脱", romaji: "yuutairidatu", eng: "ザタッチ" },
	{ kanji: "桃色吐息", romaji: "momoirotoiki", eng: "ピアノマッサージ" },
	{ kanji: "魔法美容師", romaji: "mahoubiyousi", eng: "マジカルエステ" },
	{ kanji: "薄っぺらな嘘", romaji: "usupperanauso", eng: "ドッキリテクスチャー" },
	{ kanji: "伸縮自在の愛", romaji: "sinnsyukujizainoai", eng: "バンジーガム" },
	{ kanji: "切り裂き美容師", romaji: "kirisakibiyousi", eng: "シザーハンズ" },
	{ kanji: "てのひらを太陽に", romaji: "tenohirawotaiyouni", eng: "バイオハザード" },
	{ kanji: "廻天", romaji: "kaitenn", eng: "リッパー・サイクロトロン" },
	{ kanji: "秘密の扉", romaji: "himitunotobira", eng: "マジカルワーム" },
	{ kanji: "許されざる者", romaji: "yurusarezarumono", eng: "ペインパッカー" },
	{ kanji: "太陽に灼かれて", romaji: "taiyouniyakarete", eng: "ライジングサン" },
	{ kanji: "不思議で便利な大風呂敷", romaji: "husigidebennrinaooburosiki", eng: "ファンファンクロス" },
	{ kanji: "超複眼", romaji: "tyouhukugann", eng: "スーパーアイ" },
	{ kanji: "俺の両手は機関銃", romaji: "orenoryoutehakikannjyuu", eng: "ダブルマシンガン" },
	{ kanji: "裏窓の鳥", romaji: "uramadonotori", eng: "シークレットウインドウ" },
	{ kanji: "星を継ぐもの", romaji: "hosiwotugumono", eng: "ベンジャミンバトン" },
	{ kanji: "七色弓箭", romaji: "nanairokyuusenn", eng: "レインボウ" },
	{ kanji: "戦闘演武曲", romaji: "senntouennbukyoku", eng: "バト＝レ・カンタービレ" },
	{ kanji: "念糸縫合", romaji: "nennsihougou", eng: "ねんしほうごう" },
	{ kanji: "Zombie Girl", romaji: "zonnbiga-ru", eng: "ラ・ヴィアン・ローズ" },
	{ kanji: "密室裁判", romaji: "missitusaibann", eng: "クロスゲーム" },
	{ kanji: "神の共犯者", romaji: "kaminokyouhannsya", eng: "かみのきょうはんしゃ" },
	{ kanji: "神の不在証明", romaji: "kaminohuzaisyoumei", eng: "パーフェクトプラン" },
	{ kanji: "監獄ロック", romaji: "kanngokurokku", eng: "スモーキージェイル" },
	{ kanji: "紫煙機兵隊", romaji: "siennkiheitai", eng: "ディープパープル" },
	{ kanji: "恋のエチュード", romaji: "koinoetyu-do", eng: "サイキンオセン" },
	{ kanji: "墨攻", romaji: "bokukou", eng: "LSDF" },
	{ kanji: "爆発的推進力", romaji: "bakuhatutekisuisinnryoku", eng: "オーラバースト" },
	{ kanji: "双頭の蛇の正体", romaji: "soutounohebinosyoutai", eng: "サンダースネイク" },
	{ kanji: "双頭の蛇による二重唱", romaji: "soutounohebiniyorunijyuusyou", eng: "ソングオブディフェンス" },
	{ kanji: "体は全部知っている", romaji: "karadahazennbusitteiru", eng: "ボディアンドソウル" },
	{ kanji: "14人の悪魔", romaji: "14ninnnoakuma", eng: "じゅうよにんのあくま" },
	{ kanji: "TUBE", romaji: "tyu-bu", eng: "イナムラ" },
	{ kanji: "渦波", romaji: "uzunami", eng: "トルネイヴ" },
	{ kanji: "大波", romaji: "oonami", eng: "ビックウォール" },
	{ kanji: "謝債発行機", romaji: "syasaihakkouki", eng: "レンタルポッド" },
	{ kanji: "漆黒の処刑台", romaji: "sikkokunosyokeidai", eng: "オンバサラ" },
	{ kanji: "卵男", romaji: "tamagootoko", eng: "ミサイルマン" },
	{ kanji: "超破壊拳", romaji: "tyouhakaikenn", eng: "ビックバンインパクト" },
	{ kanji: "裏窓", romaji: "uramado", eng: "リトルアイ" },
	{ kanji: "命の音", romaji: "inotinooto", eng: "カウントダウン" },
	{ kanji: "11人いる", romaji: "11ninniru", eng: "サイレントマジョリティ" },
	{ kanji: "damage", romaji: "dame-ji", eng: "ダメージ" }
];

//アニメ、漫画
export const comicAndAnimeWords = [
	{ kanji: "アオアシ", romaji: "aoasi", eng: "Aoashi" },
	{
		kanji: "あの日見た花の名前を僕達はまだ知らない",
		romaji: "anohimitahananonamaewobokutatihamadasiranai",
		eng: "Anohana: The Flower We Saw That Day"
	},
	{ kanji: "阿波連さんははかれない", romaji: "aharennsannhahakarenai", eng: "Aharen-san Is Indecipherable" },
	{ kanji: "甘城ブリリアントパーク", romaji: "amagiburirianntopa-ku", eng: "Amagi Brilliant Park" },
	{ kanji: "アルドノア・ゼロ", romaji: "arudonoazero", eng: "Aldnoah.Zero" },
	{ kanji: "暗殺教室", romaji: "annsatukyousitu", eng: "Assassination Classroom" },
	{ kanji: "異世界おじさん", romaji: "isekaiojisann", eng: "Uncle from Another World" },
	{
		kanji: "痛いのは嫌なので防御力に極振りしたいと思います",
		romaji: "itainohaiyananodebougyoryokunikyokuhurisitaitoomoimasu",
		eng: "BOFURI: I Don’t Want to Get Hurt, So I’ll Max Out My Defense"
	},
	{ kanji: "イナズマイレブン", romaji: "inazumairebunn", eng: "Inazuma Eleven" },
	{ kanji: "ヴァイオレット エヴァーガーデン", romaji: "vaioretto eva-ga-denn", eng: "Violet Evergarden" },
	{ kanji: "ヴィンラント サガ", romaji: "vinnrannto saga", eng: "Vinland Saga" },
	{ kanji: "映像研には手を出すな！", romaji: "eizoukennnihatewodasuna!", eng: "Keep Your Hands Off Eizouken!" },
	{ kanji: "86-エイティシックス-", romaji: "86-eitelisikkusu-", eng: "EIGHTY SIX" },
	{ kanji: "エルフェンリート", romaji: "erufennri-to", eng: "Elfen Lied" },
	{ kanji: "エロマンガ先生", romaji: "eromanngasennsei", eng: "Eromanga Sensei" },
	{ kanji: "炎炎ノ消防隊", romaji: "ennennnosyouboutai", eng: "Fire Force" },
	{ kanji: "王様ランキング", romaji: "ousamarannkinngu", eng: "Ranking of Kings" },
	{ kanji: "桜蘭高校ホスト部", romaji: "ourannkoukouhosutobu", eng: "Ouran High School Host Club" },
	{ kanji: "狼と香辛料", romaji: "ookamitokousinnryou", eng: "Spice and Wolf" },
	{ kanji: "オーバーロード", romaji: "o-ba-ro-do", eng: "Overlord" },
	{ kanji: "推しの子", romaji: "osinoko", eng: "Oshi No Ko" },
	{ kanji: "おそ松さん", romaji: "osomatusann", eng: "Osomatsu-san" },
	{ kanji: "オッドタクシー", romaji: "oddotakusi-", eng: "ODDTAXI" },
	{ kanji: "俺の妹がこんなに可愛いわけがない", romaji: "orenoimoutogakonnnanikawaiiwakeganai", eng: "OREIMO" },
	{ kanji: "終わりのセラフ", romaji: "owarinoserahu", eng: "Seraph of the end" },
	{ kanji: "ガールズ＆パンツァー", romaji: "ga-ruzu&panntsa-", eng: "GIRLS und PANZER" },
	{ kanji: "怪獣8号", romaji: "kaijyuu8gou", eng: "Kaiju No. 8" },
	{ kanji: "カウボーイビパップ", romaji: "kaubo-ibibappu", eng: "Cowboy Bebop" },
	{ kanji: "かくしごと", romaji: "kakusigoto", eng: "Kakushigoto" },
	{
		kanji: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～",
		romaji: "kaguyasamahakokurasetai~tennsaitatinorennaizunousenn~",
		eng: "Kaguya-sama: Love Is War"
	},
	{ kanji: "風の谷のナウシカ", romaji: "kazenotaninonausika", eng: "Nausicaa of the valley of the wind" },
	{ kanji: "がっこうぐらし！", romaji: "gakkougurasi!", eng: "SCHOOL-LIVE!" },
	{ kanji: "彼方のアストラ", romaji: "kanatanoasutora", eng: "Astra Lost in Space" },
	{ kanji: "彼女、お借りします", romaji: "kanojyo,okarisimasu", eng: "Rent a girlfriend" },
	{ kanji: "神様になった日", romaji: "kamisamaninattahi", eng: "The Day I Became a God" },
	{ kanji: "からかい上手の高木さん", romaji: "karakaijyouzunotakagisann", eng: "Teasing Master Takagi-San" },
	{ kanji: "可愛いだけじゃない式守さん", romaji: "kawaiidakejyanaisikimorisann", eng: "Shikimori's Not Just a Cutie" },
	{ kanji: "寄生獣", romaji: "kiseijyuu", eng: "Parasyte" },
	{ kanji: "機動戦士ガンダム", romaji: "kidousennsiganndamu", eng: "Mobile Suit Gundam" },
	{
		kanji: "機動戦士ガンダム 水星の魔女",
		romaji: "kidousennsiganndamu suiseinomajyo",
		eng: "Mobile Suit Gundam: The Witch from Mercury"
	},
	{
		kanji: "機動戦士ガンダム 鉄血のオルフェンズ",
		romaji: "kidousennsiganndamu tekketunoorufennzu",
		eng: "Mobile Suit Gundam: Iron-Blooded Orphans"
	},
	{ kanji: "鬼滅の刃", romaji: "kimetunoyaiba", eng: "Demon Slayer" },
	{ kanji: "ギルティクラウン", romaji: "giruthikuraunn", eng: "The Everlasting Guilty Crown" },
	{ kanji: "キルラキル", romaji: "kirurakiru", eng: "KILL la KILL" },
	{ kanji: "キングダム", romaji: "kinngudamu", eng: "Kingdom" },
	{ kanji: "銀魂", romaji: "ginntama", eng: "Gin Tama" },
	{ kanji: "銀の匙", romaji: "ginnnosaji", eng: "Silver Spoon" },
	{ kanji: "クラナド", romaji: "kuranado", eng: "CLANNAD" },
	{ kanji: "ぐらんぶる", romaji: "gurannburu", eng: "Grand Blue" },
	{ kanji: "黒子のバスケ", romaji: "kurokonobasuke", eng: "Kuroko's Basketball" },
	{ kanji: "群青のファンファーレ", romaji: "gunnjyounofannfa-re", eng: "Fanfare of Adolescence" },
	{ kanji: "けいおん！", romaji: "keionn!", eng: "K-ON!" },
	{
		kanji: "ゲート 自衛隊彼の地にて斯く戦えり",
		romaji: "ge-to jieitaikanotinitekakutatakaeri",
		eng: "GATE： Where the JSDF Fought"
	},
	{ kanji: "血界戦線", romaji: "kekkaisennsenn", eng: "Blood Blockade Battlefront" },
	{ kanji: "月刊少女 野崎くん", romaji: "gekkannsyoujyo nozakikunn", eng: "MONTHLY GIRLS NOZAKI-KUN" },
	{ kanji: "攻殻機動隊", romaji: "koukakukidoutai", eng: "GHOST IN THE SHELL" },
	{ kanji: "甲鉄城のカバネリ", romaji: "koutetujyounokabaneri", eng: "Kabaneri of the Iron Fortress" },
	{ kanji: "聲の形", romaji: "koenokatati", eng: "A Silent Voice" },
	{
		kanji: "コードギアス 反逆のルルーシュ",
		romaji: "ko-dogiasu hanngyakunoruru-syu",
		eng: "CODE GEASS Lelouch of the Rebellion"
	},
	{ kanji: "ゴールデンカムイ", romaji: "go-rudennkamui", eng: "Golden Kamuy" },
	{ kanji: "ご注文はうさぎですか？", romaji: "gotyuumonnhausagidesuka?", eng: "Is the Order a Rabbit?" },
	{ kanji: "五等分の花嫁", romaji: "gotoubunnnohanayome", eng: "The Quintessential Quintuplets" },
	{
		kanji: "この素晴らしい世界に祝福を！",
		romaji: "konosubarasiisekainisyukuhukuwo!",
		eng: "Konosuba: God's Blessing on This Wonderful World!"
	},
	{
		kanji: "この素晴らしい世界に爆焔を！",
		romaji: "konosubarasiisekainibakuennwo!",
		eng: "KonoSuba: An Explosion on This Wonderful World!"
	},
	{ kanji: "小林さんちのメイドラゴン", romaji: "kobayasisanntinomeidoragonn", eng: "Miss Kobayashi's Dragon Maid" },
	{ kanji: "古見さんは、コミュ症です。", romaji: "komisannha,komyusyoudesu", eng: "Komi Can't Communicate" },
	{ kanji: "金色のガッシュベル!!", romaji: "konnjikinogassyuberu!", eng: "Zatch Bell!" },
	{ kanji: "サイコパス", romaji: "saikopasu", eng: "PSYCHO-PASS" },
	{
		kanji: "冴えない彼女の育てかた",
		romaji: "saenaikanojyonosodatekata",
		eng: "How to Raise a Boring Girlfriend"
	},
	{ kanji: "さくら荘のペットな彼女", romaji: "sakurasounopettonakanojyo", eng: "The Pet Girl of Sakurasou" },
	{ kanji: "サマーウォーズ", romaji: "sama-who-zu", eng: "SUMMER WARS" },
	{ kanji: "三月のライオン", romaji: "sanngatunoraionn", eng: "MARCH COMES IN LIKE A LION" },
	{ kanji: "四月は君の嘘", romaji: "sigatuhakiminouso", eng: "Your Lie in April" },
	{ kanji: "地獄楽", romaji: "jigokuraku", eng: "Hell's Paradise" },
	{ kanji: "呪術廻戦", romaji: "jyujyutukaisenn", eng: "Jujutsu Kaisen" },
	{ kanji: "シュタインズゲート", romaji: "syutainnzuge-to", eng: "STEINS;GATE" },
	{ kanji: "女子高生の無駄づかい", romaji: "jyosikouseinomudadukai", eng: "Wasteful Days of High School Girl" },
	{
		kanji: "終末なにしてますか？忙しいですか？救ってもらっていいですか？",
		romaji: "syuumatunanisitemasuka?isogasiidesuka?sukuttemoratteiidesuka?",
		eng: "WorldEnd: What Do You Do at the End of the World? Are You Busy? Will You Save Us?"
	},
	{ kanji: "ジョジョの奇妙な冒険", romaji: "jyojyonokimyounaboukenn", eng: "JoJo's Bizarre Adventure" },
	{ kanji: "SHIROBAKO", romaji: "shirobako", eng: "Shirobako" },
	{ kanji: "進撃の巨人", romaji: "sinngekinokyojinn", eng: "Attack on Titan" },
	{ kanji: "新世界より", romaji: "sinnsekaiyori", eng: "From the New World" },
	{ kanji: "新世紀エヴァンゲリオン", romaji: "sinnseikievanngerionn", eng: "Neon Genesis EVANGELION" },
	{ kanji: "スプリガン", romaji: "supurigann", eng: "SPRIGGAN" },
	{ kanji: "スラムダンク", romaji: "suramudannku", eng: "SLAM DUNK" },
	{ kanji: "涼宮ハルヒの憂鬱", romaji: "suzumiyaharuhinoyuuutu", eng: "The Melancholy of Haruhi Suzumiya" },
	{
		kanji: "青春ブタ野郎はバニーガール先輩の夢を見ない",
		romaji: "seisyunnbutayarouhabani-ga-rusennpainoyumewominai",
		eng: "Rascal Does Not Dream of Bunny Girl Senpai"
	},
	{
		kanji: "青春ブタ野郎はゆめみる少女の夢を見ない",
		romaji: "seisyunnbutayarouhayumemirusyoujyonoyumewominai",
		eng: "Rascal Does Not Dream of a Dreaming Girl"
	},
	{ kanji: "千と千尋の神隠し", romaji: "senntotihironokamikakusi", eng: "Spirited Away" },
	{ kanji: "ソードアート オンライン", romaji: "so-doa-to onnrainn", eng: "Sword Art Online" },
	{ kanji: "その着せ替え人形は恋をする", romaji: "sonokisekaeninngyouhakoiwosuru", eng: "My Dress-Up Darling" },
	{ kanji: "宇宙よりも遠い場所", romaji: "utyuuyorimotooibasyo", eng: "A Place Further than the Universe" },
	{ kanji: "ゾンビ ランド サガ", romaji: "zonnbiranndosaga", eng: "Zombie Land Saga" },
	{ kanji: "ダーリン イン ザ フランキス", romaji: "da-rinn inn za hurannkisu", eng: "DARLING in the FRANXX" },
	{ kanji: "盾の勇者の成り上がり", romaji: "tatenoyuusyanonariagari", eng: "The Rising of the Shield Hero" },
	{ kanji: "男子高校生の日常", romaji: "dannsikoukouseinonitijyou", eng: "Daily Lives of high school boys" },
	{
		kanji: "ダンジョンに出会いを求めるのは間違っているだろうか",
		romaji: "dannjyonnnideaiwomotomerunohamatigatteirudarouka",
		eng: "Is It Wrong to Try to Pick Up Girls in a Dungeon?"
	},
	{ kanji: "チェンソーマン", romaji: "tyennso-mann", eng: "Chainsaw Man" },
	{ kanji: "ちはやふる", romaji: "tihayahuru", eng: "Chihayafuru" },
	{ kanji: "中二病でも恋がしたい！", romaji: "tyuunibyoudemokoigasitai", eng: "Love, Chunibyo & Other Delusions" },
	{ kanji: "月がきれい", romaji: "tukigakirei", eng: "as the moon, so beautiful" },
	{ kanji: "デート ア ライブ", romaji: "de-to a raibu", eng: "DATE A LIVE" },
	{ kanji: "デスノート", romaji: "desuno-to", eng: "DEATH NOTE" },
	{ kanji: "デュラララ!!", romaji: "dhurarara!!", eng: "Durarara!!" },
	{ kanji: "天空の城ラピュタ", romaji: "tennkuunosirorapyuta", eng: "Castle in the Sky" },
	{ kanji: "天元突破グレンラガン", romaji: "tenngenntoppagurennragann", eng: "Gurren Lagann" },
	{
		kanji: "転生したらスライムだった件",
		romaji: "tennseisitarasuraimudattakenn",
		eng: "That Time I Got Reincarnated as a Slime"
	},
	{ kanji: "とある科学の超電磁砲", romaji: "toarukagakunore-rugann", eng: "A Certain Scientific Railgun" },
	{ kanji: "東京喰種トーキョーグール", romaji: "toukyougu-ru", eng: "Tokyo Ghoul" },
	{ kanji: "東京24区", romaji: "toukyou24ku", eng: "TOKYO TWENTY FOURTH WARD" },
	{ kanji: "東京マグニチュード8.0", romaji: "toukyoumagunityu-do8.0", eng: "Tokyo Magnitude 8.0: Complete Collection" },
	{ kanji: "東京リベンジャーズ", romaji: "toukyouribennjya-zu", eng: "Tokyo Revengers" },
	{ kanji: "時をかける少女", romaji: "tokiwokakerusyoujyo", eng: "Girl Who Leapt Through Time" },
	{ kanji: "ドクターストーン", romaji: "dokuta-suto-nn", eng: "Dr.STONE" },
	{ kanji: "となりのトトロ", romaji: "tonarinototoro", eng: "My Neighbor Totoro" },
	{ kanji: "ドラえもん", romaji: "doraemonn", eng: "Doraemon" },
	{ kanji: "ドラゴンボール超", romaji: "doragonnbo-rusu-pa-", eng: "Dragon Ball Super" },
	{ kanji: "とらドラ！", romaji: "toradora!", eng: "Toradora!" },
	{
		kanji: "とんでもスキルで異世界放浪メシ",
		romaji: "tonndemosukirudeisekaihouroumesi",
		eng: "Campfire Cooking in Another World with My Absurd Skill"
	},
	{ kanji: "凪のあすから", romaji: "naginoasukara", eng: "A Lull in the Sea" },
	{ kanji: "夏目友人帳", romaji: "nasumeyuujinntyou", eng: "Natsume's Book of Friends" },
	{ kanji: "七つの大罪", romaji: "nanatunotaizai", eng: "The Seven Deadly Sins" },
	{ kanji: "ナルト", romaji: "naruto", eng: "NARUTO" },
	{ kanji: "ニセコイ", romaji: "nisekoi", eng: "Nisekoi" },
	{ kanji: "日常", romaji: "nitijyou", eng: "NICHIJOU: MY ORDINARY LIFE" },
	{ kanji: "ノーゲーム ノーライフ", romaji: "no-ge-mu no-raihu", eng: "NO GAME NO LIFE" },
	{ kanji: "のんのんびより", romaji: "nonnnonnbiyori", eng: "Non Non Biyori" },
	{ kanji: "ハイキュー!!", romaji: "haikyu-!!", eng: "Haikyu!!" },
	{ kanji: "ハイスコアガール", romaji: "haisukoaga-ru", eng: "Hi Score Girl" },
	{ kanji: "灰と幻想のグリムガル", romaji: "haitogennsounogurimugaru", eng: "Grimgar of Fantasy and Ash" },
	{ kanji: "鋼の錬金術師", romaji: "haganenorennkinnjyutusi", eng: "FULLMETAL ALCHEMIST" },
	{ kanji: "はたらく魔王さま！", romaji: "hatarakumaousama!", eng: "The Devil Is a Part-Timer" },
	{ kanji: "花咲くいろは", romaji: "hanasakuiroha", eng: "Hanasaku Iroha" },
	{ kanji: "ばらかもん", romaji: "barakamonn", eng: "Barakamon" },
	{ kanji: "パリピ孔明", romaji: "paripikoumei", eng: "Ya Boy Kongming!" },
	{ kanji: "ハンターハンター", romaji: "hannta-hannta-", eng: "HUNTER×HUNTER" },
	{ kanji: "東のエデン", romaji: "higasinoedenn", eng: "Eden of The East" },
	{ kanji: "ヒカルの碁", romaji: "hikarunogo", eng: "Hikaru no Go" },
	{ kanji: "ひぐらしのなく頃に", romaji: "higurasinonakukoroni", eng: "WHEN THEY CRY" },
	{ kanji: "美少女戦士セーラームーン", romaji: "bisyoujyosennsise-ra-mu-nn", eng: "Sailor Moon" },
	{ kanji: "ヒナまつり", romaji: "hinamaturi", eng: "Hinamatsuri" },
	{ kanji: "響け！ユーフォニアム", romaji: "hibike!yu-foniamu", eng: "Sound! Euphonium" },
	{ kanji: "氷菓", romaji: "hyouka", eng: "HYOUKA" },
	{ kanji: "ピンポン", romaji: "pinnponn", eng: "PingPong" },
	{ kanji: "プラスティックメモリーズ", romaji: "purasuthikkumemori-zu", eng: "Plastic Memories" },
	{ kanji: "ブラック ラグーン", romaji: "burakku ragu-nn", eng: "BLACK LAGOON" },
	{ kanji: "プラネテス", romaji: "puranetesu", eng: "PLANETES" },
	{ kanji: "ブリーチ", romaji: "buri-ti", eng: "BLEACH" },
	{ kanji: "フルーツバスケット", romaji: "huru-tubasuketto", eng: "Fruits Basket" },
	{ kanji: "ブルーロック", romaji: "buru-rokku", eng: "BLUELOCK" },
	{ kanji: "文豪ストレイドッグス", romaji: "bunngousutoreidoggusu", eng: "Bungo Stray Dogs" },
	{ kanji: "僕だけがいない街", romaji: "bokudakegainaimati", eng: "Erased" },
	{ kanji: "僕の心のヤバイやつ", romaji: "bokunokokoronoyabaiyatu", eng: "The Dangers in My Heart" },
	{ kanji: "僕のヒーローアカデミア", romaji: "bokunohi-ro-akademia", eng: "My Hero Academia" },
	{ kanji: "ぼっち ざ ろっく！", romaji: "botti za rokku!", eng: "Bocchi the Rock!" },
	{ kanji: "マイホームヒーロー", romaji: "maiho-muhi-ro-", eng: "My Home Hero" },
	{ kanji: "マクロスF", romaji: "makurosuF", eng: "MACROSS Frontier" },
	{ kanji: "魔法科高校の劣等生", romaji: "mahoukakoukounorettousei", eng: "The Irregular at Magic High School" },
	{ kanji: "魔法少女まどかマギカ", romaji: "mahousyoujyomadokamagika", eng: "Puella Magi Madoka Magica" },
	{ kanji: "魔法使いの嫁", romaji: "mahoutukainoyome", eng: "The Ancient Magus' Bride" },
	{ kanji: "輪るピングドラム", romaji: "mawarupinngudoramu", eng: "Mawaru Penguindrum" },
	{ kanji: "未来日記", romaji: "mirainikki", eng: "Future Diary" },
	{ kanji: "蟲師", romaji: "musisi", eng: "Mushishi" },
	{
		kanji: "無職転生 ～異世界行ったら本気だす～",
		romaji: "musyokutennsei~isekaiittarahonnkidasu~",
		eng: "Mushoku Tensei: Jobless Reincarnation"
	},
	{ kanji: "名探偵コナン", romaji: "meitannteikonann", eng: "Detective Conan / Case Closed" },
	{ kanji: "メイドインアビス", romaji: "meidoinnabisu", eng: "MADE IN ABYSS" },
	{ kanji: "もののけ姫", romaji: "mononokehime", eng: "Princess Mononoke" },
	{ kanji: "モブサイコ100", romaji: "mobusaiko100", eng: "Mob Psycho 100" },
	{
		kanji: "Re:ゼロから始める異世界生活",
		romaji: "Re:zerokarahajimeruisekaiseikatu",
		eng: "Re:Zero -Starting Life in Another World-"
	},
	{ kanji: "化物語", romaji: "bakemonogatari", eng: "BAKEMONOGATARI" },
	{ kanji: "約束のネバーランド", romaji: "yakusokunoneba-ranndo", eng: "The Promised Neverland" },
	{
		kanji: "やはり俺の青春ラブコメはまちがっている。",
		romaji: "yahariorenoseisyunnrabukomehamatigatteiru",
		eng: "My Youth Romantic Comedy Is Wrong As I Expected."
	},
	{
		kanji: "山田くんと Lv999 の恋をする",
		romaji: "yamadakunntoLv999nokoiwosuru",
		eng: "My Love Story with Yamada-kun at Lv999"
	},
	{ kanji: "結城友奈は勇者である", romaji: "yuukiyuunahayuusyadearu", eng: "YUKI YUNA IS A HERO" },
	{ kanji: "勇者、辞めます", romaji: "yuusya,yamemasu", eng: "I'm Quitting Heroing" },
	{ kanji: "幽遊白書", romaji: "yuuyuuhakusyo", eng: "YuYu Hakusho" },
	{ kanji: "ユーリ!!! オン アイス", romaji: "yu-ri!!! onn aisu", eng: "YURI!!! on ICE" },
	{ kanji: "ゆるキャン", romaji: "yurukyann", eng: "Laid back camp" },
	{
		kanji: "ようこそ実力至上主義の教室へ",
		romaji: "youkosojituryokusijyousyuginokyousituhe",
		eng: "Classroom of the Elite"
	},
	{ kanji: "幼女戦記", romaji: "youjyosennki", eng: "The Saga of Tanya the Evil" },
	{ kanji: "四畳半神話大系", romaji: "yojyouhannsinnwataikei", eng: "The Tatami Galaxy" },
	{ kanji: "ヨルムンガンド", romaji: "yorumunnganndo", eng: "Jormungand" },
	{ kanji: "弱虫ペダル", romaji: "yowamusipedaru", eng: "Yowamushi Pedal" },
	{ kanji: "らきすた", romaji: "rakisuta", eng: "Lucky Star" },
	{ kanji: "ラブライブ！", romaji: "raburaibu!", eng: "Love Live!" },
	{ kanji: "リーマンズクラブ", romaji: "ri-mannzukurabu", eng: "Salaryman's Club" },
	{ kanji: "リライフ", romaji: "riraihu", eng: "ReLIFE" },
	{ kanji: "ルパン三世", romaji: "rupannsannsei", eng: "Lupin the Third" },
	{ kanji: "レクリエイターズ", romaji: "rekurieita-zu", eng: "Re:CREATORS" },
	{ kanji: "ログ ホライズン", romaji: "rogu horaizunn", eng: "LOG HORIZON" },
	{ kanji: "ワールドトリガー", romaji: "wa-rudotoriga-", eng: "WORLD TRIGGER" },
	{ kanji: "私に天使が舞い降りた！", romaji: "watasinitennsigamaiorita!", eng: "The angel came to me from the sky" },
	{ kanji: "ワンパンマン", romaji: "wannpannmann", eng: "One Punch-Man" },
	{ kanji: "ワンピース", romaji: "wannpi-su", eng: "ONE PIECE" }
];

//ロマンス小説の言葉
export const romanceWords = [];

//時代小説の言葉
export const historyWords = [];

//ホラー小説の言葉
export const horrorWords = [];

//冒険小説の言葉
export const adventureWords = [];

//サスペンス小説の言葉
export const suspenseWords = [];
